/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectofinal;

import Clases.Persona;
import Clases.Tarea;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.tree.DefaultMutableTreeNode;
import static proyectofinal.Main.ListUssers;

public class Drive extends javax.swing.JFrame {

    /**
     * Creates new form Drive
     */
    public Drive() {
        initComponents();
        setLocationRelativeTo(this);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        Nombre_Usuario_Label = new javax.swing.JLabel();
        Grupps = new javax.swing.JDialog();
        jPanel3 = new javax.swing.JPanel();
        NombreLista = new javax.swing.JLabel();
        HEADERCOSO1 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jl_personas = new javax.swing.JList();
        jScrollPane5 = new javax.swing.JScrollPane();
        jl_Grupos2 = new javax.swing.JList();
        HEADERCOSO2 = new javax.swing.JLabel();
        TareasEliminarTareasBoton2 = new javax.swing.JButton();
        HEADERCOSO6 = new javax.swing.JLabel();
        NuevoG = new javax.swing.JDialog();
        jPanel4 = new javax.swing.JPanel();
        NombreLista1 = new javax.swing.JLabel();
        HEADERCOSO3 = new javax.swing.JLabel();
        Agregarintegrante = new javax.swing.JButton();
        Nombre_Usuario_Label1 = new javax.swing.JLabel();
        Nombre_Usuario_Label3 = new javax.swing.JLabel();
        NombreGrupoTF = new javax.swing.JTextField();
        CB_Usuario_Modificar_AT = new javax.swing.JComboBox<>();
        TareasEliminarTareasBoton4 = new javax.swing.JButton();
        Grupps1 = new javax.swing.JDialog();
        jPanel5 = new javax.swing.JPanel();
        NombreLista2 = new javax.swing.JLabel();
        HEADERCOSO4 = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        jl_personas2 = new javax.swing.JList();
        jScrollPane8 = new javax.swing.JScrollPane();
        jl_Grupos3 = new javax.swing.JList();
        HEADERCOSO5 = new javax.swing.JLabel();
        HEADERCOSO7 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();
        HEADERCOSO = new javax.swing.JLabel();
        PANELLATERAL1 = new javax.swing.JPanel();
        jLabel25 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        CrearArchivoBoton1 = new javax.swing.JButton();
        jPanel10 = new javax.swing.JPanel();
        AgregarArchivoBoton1 = new javax.swing.JButton();
        jPanel11 = new javax.swing.JPanel();
        TareasCompletasTareasBoton1 = new javax.swing.JButton();
        jPanel12 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jl_personas1 = new javax.swing.JList();
        BOTONUNIVERSSAL = new javax.swing.JLabel();
        GruposBoton2 = new javax.swing.JButton();
        jPanel13 = new javax.swing.JPanel();
        GruposBoton3 = new javax.swing.JButton();
        jPanel14 = new javax.swing.JPanel();

        jMenuItem1.setBackground(new java.awt.Color(78, 148, 79));
        jMenuItem1.setFont(new java.awt.Font("Roboto Medium", 1, 12)); // NOI18N
        jMenuItem1.setForeground(new java.awt.Color(78, 148, 79));
        jMenuItem1.setText("Eliminar");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jPopupMenu1.add(jMenuItem1);

        jMenuItem2.setText("Compartir");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jPopupMenu1.add(jMenuItem2);

        Nombre_Usuario_Label.setFont(new java.awt.Font("Roboto Medium", 1, 14)); // NOI18N
        Nombre_Usuario_Label.setForeground(new java.awt.Color(78, 148, 79));
        Nombre_Usuario_Label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Nombre_Usuario_Label.setText("Bienvenido Avelardo");
        Nombre_Usuario_Label.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Nombre_Usuario_Label.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jPanel3.setBackground(new java.awt.Color(247, 246, 220));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        NombreLista.setBackground(new java.awt.Color(247, 246, 220));
        NombreLista.setFont(new java.awt.Font("Roboto Medium", 1, 18)); // NOI18N
        NombreLista.setForeground(new java.awt.Color(78, 148, 79));
        jPanel3.add(NombreLista, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        HEADERCOSO1.setFont(new java.awt.Font("Roboto Medium", 1, 36)); // NOI18N
        HEADERCOSO1.setForeground(new java.awt.Color(78, 148, 79));
        HEADERCOSO1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        HEADERCOSO1.setText("Id integrantes");
        HEADERCOSO1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        HEADERCOSO1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel3.add(HEADERCOSO1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 70, -1, 40));

        jl_personas.setBackground(new java.awt.Color(233, 239, 192));
        jl_personas.setFont(new java.awt.Font("Roboto Medium", 1, 12)); // NOI18N
        jl_personas.setForeground(new java.awt.Color(78, 148, 79));
        jl_personas.setModel(new DefaultListModel());
        jl_personas.setSelectionBackground(new java.awt.Color(78, 148, 79));
        jl_personas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jl_personasMouseClicked(evt);
            }
        });
        jl_personas.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jl_personasKeyPressed(evt);
            }
        });
        jScrollPane3.setViewportView(jl_personas);

        jPanel3.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 130, 420, 230));

        jl_Grupos2.setBackground(new java.awt.Color(233, 239, 192));
        jl_Grupos2.setFont(new java.awt.Font("Roboto Medium", 1, 12)); // NOI18N
        jl_Grupos2.setForeground(new java.awt.Color(78, 148, 79));
        jl_Grupos2.setModel(new DefaultListModel());
        jl_Grupos2.setSelectionBackground(new java.awt.Color(78, 148, 79));
        jl_Grupos2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jl_Grupos2MouseClicked(evt);
            }
        });
        jl_Grupos2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jl_Grupos2KeyPressed(evt);
            }
        });
        jScrollPane5.setViewportView(jl_Grupos2);

        jPanel3.add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 200, 290));

        HEADERCOSO2.setFont(new java.awt.Font("Roboto Medium", 1, 36)); // NOI18N
        HEADERCOSO2.setForeground(new java.awt.Color(78, 148, 79));
        HEADERCOSO2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        HEADERCOSO2.setText("G r u p o s");
        HEADERCOSO2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        HEADERCOSO2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel3.add(HEADERCOSO2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, 40));

        TareasEliminarTareasBoton2.setBackground(new java.awt.Color(78, 148, 79));
        TareasEliminarTareasBoton2.setFont(new java.awt.Font("Roboto Medium", 1, 14)); // NOI18N
        TareasEliminarTareasBoton2.setForeground(new java.awt.Color(233, 239, 192));
        TareasEliminarTareasBoton2.setText("        Crear Nuevo Grupo");
        TareasEliminarTareasBoton2.setBorder(null);
        TareasEliminarTareasBoton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        TareasEliminarTareasBoton2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        TareasEliminarTareasBoton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TareasEliminarTareasBoton2ActionPerformed(evt);
            }
        });
        jPanel3.add(TareasEliminarTareasBoton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 400, 190, 40));

        HEADERCOSO6.setFont(new java.awt.Font("Roboto Medium", 1, 36)); // NOI18N
        HEADERCOSO6.setForeground(new java.awt.Color(78, 148, 79));
        HEADERCOSO6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        HEADERCOSO6.setText("G r u p o s");
        HEADERCOSO6.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        HEADERCOSO6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel3.add(HEADERCOSO6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, 40));

        javax.swing.GroupLayout GruppsLayout = new javax.swing.GroupLayout(Grupps.getContentPane());
        Grupps.getContentPane().setLayout(GruppsLayout);
        GruppsLayout.setHorizontalGroup(
            GruppsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 708, Short.MAX_VALUE)
            .addGroup(GruppsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 708, Short.MAX_VALUE))
        );
        GruppsLayout.setVerticalGroup(
            GruppsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 464, Short.MAX_VALUE)
            .addGroup(GruppsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 464, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(247, 246, 220));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        NombreLista1.setBackground(new java.awt.Color(247, 246, 220));
        NombreLista1.setFont(new java.awt.Font("Roboto Medium", 1, 18)); // NOI18N
        NombreLista1.setForeground(new java.awt.Color(78, 148, 79));
        jPanel4.add(NombreLista1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        HEADERCOSO3.setFont(new java.awt.Font("Roboto Medium", 1, 36)); // NOI18N
        HEADERCOSO3.setForeground(new java.awt.Color(78, 148, 79));
        HEADERCOSO3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        HEADERCOSO3.setText("N u e v o   G r u p o");
        HEADERCOSO3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        HEADERCOSO3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel4.add(HEADERCOSO3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 310, 40));

        Agregarintegrante.setBackground(new java.awt.Color(78, 148, 79));
        Agregarintegrante.setFont(new java.awt.Font("Roboto Medium", 1, 14)); // NOI18N
        Agregarintegrante.setForeground(new java.awt.Color(233, 239, 192));
        Agregarintegrante.setText("          Agregar");
        Agregarintegrante.setBorder(null);
        Agregarintegrante.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Agregarintegrante.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Agregarintegrante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgregarintegranteActionPerformed(evt);
            }
        });
        jPanel4.add(Agregarintegrante, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, 120, 40));

        Nombre_Usuario_Label1.setFont(new java.awt.Font("Roboto Medium", 1, 14)); // NOI18N
        Nombre_Usuario_Label1.setForeground(new java.awt.Color(78, 148, 79));
        Nombre_Usuario_Label1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Nombre_Usuario_Label1.setText("Integrante Nuevo");
        Nombre_Usuario_Label1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Nombre_Usuario_Label1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel4.add(Nombre_Usuario_Label1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 120, 20));

        Nombre_Usuario_Label3.setFont(new java.awt.Font("Roboto Medium", 1, 14)); // NOI18N
        Nombre_Usuario_Label3.setForeground(new java.awt.Color(78, 148, 79));
        Nombre_Usuario_Label3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Nombre_Usuario_Label3.setText("Nombre");
        Nombre_Usuario_Label3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Nombre_Usuario_Label3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel4.add(Nombre_Usuario_Label3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 60, -1));

        NombreGrupoTF.setBackground(new java.awt.Color(180, 225, 151));
        NombreGrupoTF.setFont(new java.awt.Font("Roboto Medium", 1, 14)); // NOI18N
        NombreGrupoTF.setForeground(new java.awt.Color(78, 148, 79));
        NombreGrupoTF.setBorder(null);
        jPanel4.add(NombreGrupoTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 220, 30));

        CB_Usuario_Modificar_AT.setBackground(new java.awt.Color(180, 225, 151));
        CB_Usuario_Modificar_AT.setFont(new java.awt.Font("Roboto Medium", 1, 14)); // NOI18N
        CB_Usuario_Modificar_AT.setForeground(new java.awt.Color(78, 148, 79));
        CB_Usuario_Modificar_AT.setBorder(null);
        CB_Usuario_Modificar_AT.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                CB_Usuario_Modificar_ATItemStateChanged(evt);
            }
        });
        CB_Usuario_Modificar_AT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CB_Usuario_Modificar_ATActionPerformed(evt);
            }
        });
        jPanel4.add(CB_Usuario_Modificar_AT, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 220, 30));

        TareasEliminarTareasBoton4.setBackground(new java.awt.Color(78, 148, 79));
        TareasEliminarTareasBoton4.setFont(new java.awt.Font("Roboto Medium", 1, 14)); // NOI18N
        TareasEliminarTareasBoton4.setForeground(new java.awt.Color(233, 239, 192));
        TareasEliminarTareasBoton4.setText("        Crear Nuevo Grupo");
        TareasEliminarTareasBoton4.setBorder(null);
        TareasEliminarTareasBoton4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        TareasEliminarTareasBoton4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        TareasEliminarTareasBoton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TareasEliminarTareasBoton4ActionPerformed(evt);
            }
        });
        jPanel4.add(TareasEliminarTareasBoton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, 190, 40));

        javax.swing.GroupLayout NuevoGLayout = new javax.swing.GroupLayout(NuevoG.getContentPane());
        NuevoG.getContentPane().setLayout(NuevoGLayout);
        NuevoGLayout.setHorizontalGroup(
            NuevoGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 344, Short.MAX_VALUE)
            .addGroup(NuevoGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(NuevoGLayout.createSequentialGroup()
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 344, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        NuevoGLayout.setVerticalGroup(
            NuevoGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 440, Short.MAX_VALUE)
            .addGroup(NuevoGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel5.setBackground(new java.awt.Color(247, 246, 220));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        NombreLista2.setBackground(new java.awt.Color(247, 246, 220));
        NombreLista2.setFont(new java.awt.Font("Roboto Medium", 1, 18)); // NOI18N
        NombreLista2.setForeground(new java.awt.Color(78, 148, 79));
        jPanel5.add(NombreLista2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        HEADERCOSO4.setFont(new java.awt.Font("Roboto Medium", 1, 36)); // NOI18N
        HEADERCOSO4.setForeground(new java.awt.Color(78, 148, 79));
        HEADERCOSO4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        HEADERCOSO4.setText("Id integrantes");
        HEADERCOSO4.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        HEADERCOSO4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel5.add(HEADERCOSO4, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 80, -1, 40));

        jl_personas2.setBackground(new java.awt.Color(233, 239, 192));
        jl_personas2.setFont(new java.awt.Font("Roboto Medium", 1, 12)); // NOI18N
        jl_personas2.setForeground(new java.awt.Color(78, 148, 79));
        jl_personas2.setModel(new DefaultListModel());
        jl_personas2.setSelectionBackground(new java.awt.Color(78, 148, 79));
        jl_personas2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jl_personas2MouseClicked(evt);
            }
        });
        jl_personas2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jl_personas2KeyPressed(evt);
            }
        });
        jScrollPane6.setViewportView(jl_personas2);

        jPanel5.add(jScrollPane6, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 150, 420, 210));

        jl_Grupos3.setBackground(new java.awt.Color(233, 239, 192));
        jl_Grupos3.setFont(new java.awt.Font("Roboto Medium", 1, 12)); // NOI18N
        jl_Grupos3.setForeground(new java.awt.Color(78, 148, 79));
        jl_Grupos3.setModel(new DefaultListModel());
        jl_Grupos3.setSelectionBackground(new java.awt.Color(78, 148, 79));
        jl_Grupos3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jl_Grupos3MouseClicked(evt);
            }
        });
        jl_Grupos3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jl_Grupos3KeyPressed(evt);
            }
        });
        jScrollPane8.setViewportView(jl_Grupos3);

        jPanel5.add(jScrollPane8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 200, 290));

        HEADERCOSO5.setFont(new java.awt.Font("Roboto Medium", 1, 36)); // NOI18N
        HEADERCOSO5.setForeground(new java.awt.Color(78, 148, 79));
        HEADERCOSO5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        HEADERCOSO5.setText("G r u p o s");
        HEADERCOSO5.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        HEADERCOSO5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel5.add(HEADERCOSO5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, 40));

        HEADERCOSO7.setFont(new java.awt.Font("Roboto Medium", 1, 36)); // NOI18N
        HEADERCOSO7.setForeground(new java.awt.Color(78, 148, 79));
        HEADERCOSO7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        HEADERCOSO7.setText("G r u p o s");
        HEADERCOSO7.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        HEADERCOSO7.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel5.add(HEADERCOSO7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, 40));

        javax.swing.GroupLayout Grupps1Layout = new javax.swing.GroupLayout(Grupps1.getContentPane());
        Grupps1.getContentPane().setLayout(Grupps1Layout);
        Grupps1Layout.setHorizontalGroup(
            Grupps1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 708, Short.MAX_VALUE)
            .addGroup(Grupps1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, 708, Short.MAX_VALUE))
        );
        Grupps1Layout.setVerticalGroup(
            Grupps1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 464, Short.MAX_VALUE)
            .addGroup(Grupps1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, 464, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(233, 239, 192));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(247, 246, 220));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tabla.setBackground(new java.awt.Color(247, 246, 220));
        tabla.setFont(new java.awt.Font("Roboto Medium", 1, 12)); // NOI18N
        tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Nombre", "Fecha", "Creador"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tabla.setComponentPopupMenu(jPopupMenu1);
        tabla.setSelectionBackground(new java.awt.Color(78, 148, 79));
        tabla.getTableHeader().setReorderingAllowed(false);
        tabla.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabla);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 800, 500));

        HEADERCOSO.setFont(new java.awt.Font("Roboto Medium", 1, 36)); // NOI18N
        HEADERCOSO.setForeground(new java.awt.Color(78, 148, 79));
        HEADERCOSO.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        HEADERCOSO.setText("Mi Unidad");
        HEADERCOSO.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        HEADERCOSO.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel2.add(HEADERCOSO, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, 40));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(238, 18, 830, 577));

        PANELLATERAL1.setBackground(new java.awt.Color(180, 225, 151));
        PANELLATERAL1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel25.setBackground(new java.awt.Color(78, 148, 79));
        jLabel25.setFont(new java.awt.Font("Roboto Medium", 1, 12)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(78, 148, 79));
        jLabel25.setText("R e c i e n t e s");
        jLabel25.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        PANELLATERAL1.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 240, 130, 40));

        jSeparator3.setBackground(new java.awt.Color(78, 148, 79));
        jSeparator3.setForeground(new java.awt.Color(78, 148, 79));
        PANELLATERAL1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 280, 220, 20));

        jSeparator4.setBackground(new java.awt.Color(78, 148, 79));
        jSeparator4.setForeground(new java.awt.Color(78, 148, 79));
        PANELLATERAL1.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 220, 20));

        CrearArchivoBoton1.setBackground(new java.awt.Color(78, 148, 79));
        CrearArchivoBoton1.setFont(new java.awt.Font("Roboto Medium", 1, 14)); // NOI18N
        CrearArchivoBoton1.setForeground(new java.awt.Color(233, 239, 192));
        CrearArchivoBoton1.setText("Crear Archivo");
        CrearArchivoBoton1.setBorder(null);
        CrearArchivoBoton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        CrearArchivoBoton1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        CrearArchivoBoton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CrearArchivoBoton1ActionPerformed(evt);
            }
        });
        PANELLATERAL1.add(CrearArchivoBoton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 190, 31));

        jPanel10.setBackground(new java.awt.Color(78, 148, 79));

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        PANELLATERAL1.add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 100, 31));

        AgregarArchivoBoton1.setBackground(new java.awt.Color(78, 148, 79));
        AgregarArchivoBoton1.setFont(new java.awt.Font("Roboto Medium", 1, 14)); // NOI18N
        AgregarArchivoBoton1.setForeground(new java.awt.Color(233, 239, 192));
        AgregarArchivoBoton1.setText("Agregar Archivo");
        AgregarArchivoBoton1.setBorder(null);
        AgregarArchivoBoton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        AgregarArchivoBoton1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        AgregarArchivoBoton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgregarArchivoBoton1ActionPerformed(evt);
            }
        });
        PANELLATERAL1.add(AgregarArchivoBoton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 190, 31));

        jPanel11.setBackground(new java.awt.Color(78, 148, 79));

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        PANELLATERAL1.add(jPanel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 100, 31));

        TareasCompletasTareasBoton1.setBackground(new java.awt.Color(78, 148, 79));
        TareasCompletasTareasBoton1.setFont(new java.awt.Font("Roboto Medium", 1, 14)); // NOI18N
        TareasCompletasTareasBoton1.setForeground(new java.awt.Color(233, 239, 192));
        TareasCompletasTareasBoton1.setText("Archivos Compartidos");
        TareasCompletasTareasBoton1.setBorder(null);
        TareasCompletasTareasBoton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        TareasCompletasTareasBoton1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        TareasCompletasTareasBoton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TareasCompletasTareasBoton1ActionPerformed(evt);
            }
        });
        PANELLATERAL1.add(TareasCompletasTareasBoton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 540, 190, 31));

        jPanel12.setBackground(new java.awt.Color(78, 148, 79));

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        PANELLATERAL1.add(jPanel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 540, 100, 31));

        jl_personas1.setBackground(new java.awt.Color(247, 246, 220));
        jl_personas1.setFont(new java.awt.Font("Roboto Medium", 1, 12)); // NOI18N
        jl_personas1.setForeground(new java.awt.Color(78, 148, 79));
        jl_personas1.setModel(new DefaultListModel());
        jl_personas1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jl_personas1MouseClicked(evt);
            }
        });
        jl_personas1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jl_personas1KeyPressed(evt);
            }
        });
        jScrollPane4.setViewportView(jl_personas1);

        PANELLATERAL1.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 290, 220, 240));

        BOTONUNIVERSSAL.setBackground(new java.awt.Color(78, 148, 79));
        BOTONUNIVERSSAL.setFont(new java.awt.Font("Roboto Medium", 1, 12)); // NOI18N
        BOTONUNIVERSSAL.setForeground(new java.awt.Color(78, 148, 79));
        BOTONUNIVERSSAL.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/CloudIcon.png"))); // NOI18N
        BOTONUNIVERSSAL.setText("C l o u d");
        BOTONUNIVERSSAL.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BOTONUNIVERSSAL.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BOTONUNIVERSSALMouseClicked(evt);
            }
        });
        PANELLATERAL1.add(BOTONUNIVERSSAL, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, 120, 50));

        GruposBoton2.setBackground(new java.awt.Color(78, 148, 79));
        GruposBoton2.setFont(new java.awt.Font("Roboto Medium", 1, 14)); // NOI18N
        GruposBoton2.setForeground(new java.awt.Color(233, 239, 192));
        GruposBoton2.setText("Grupos");
        GruposBoton2.setBorder(null);
        GruposBoton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        GruposBoton2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        GruposBoton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GruposBoton2ActionPerformed(evt);
            }
        });
        PANELLATERAL1.add(GruposBoton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, 190, 31));

        jPanel13.setBackground(new java.awt.Color(78, 148, 79));

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        PANELLATERAL1.add(jPanel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 100, 31));

        GruposBoton3.setBackground(new java.awt.Color(78, 148, 79));
        GruposBoton3.setFont(new java.awt.Font("Roboto Medium", 1, 14)); // NOI18N
        GruposBoton3.setForeground(new java.awt.Color(233, 239, 192));
        GruposBoton3.setText("Papelera");
        GruposBoton3.setBorder(null);
        GruposBoton3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        GruposBoton3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        GruposBoton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GruposBoton3ActionPerformed(evt);
            }
        });
        PANELLATERAL1.add(GruposBoton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, 190, 31));

        jPanel14.setBackground(new java.awt.Color(78, 148, 79));

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        PANELLATERAL1.add(jPanel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 100, 31));

        jPanel1.add(PANELLATERAL1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 610));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1090, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CrearCarpetaBoton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CrearCarpetaBoton1ActionPerformed

    }//GEN-LAST:event_CrearCarpetaBoton1ActionPerformed

    private void CrearArchivoBoton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CrearArchivoBoton1ActionPerformed

    }//GEN-LAST:event_CrearArchivoBoton1ActionPerformed

    private void AgregarArchivoBoton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgregarArchivoBoton1ActionPerformed
        JFileChooser jfc = new JFileChooser();//Instqncia fc

        int seleccion = jfc.showSaveDialog(this);  //mostrar la ventana de dialogo      
        FileWriter fw = null;
        BufferedWriter bw = null;
        if (seleccion == JFileChooser.APPROVE_OPTION) {//si preciono okay
            try {

                File fichero = null;//crear instancia file nula, la cual se le agregara una extns
                fichero = jfc.getSelectedFile();
                fw = new FileWriter(fichero);//wilewritter a archivo
                bw = new BufferedWriter(fw);//bufferded writter a el canar fw
                ArchivosI.add(new Archivo(fecha(), fichero, NewJFrame.Uactual.getID()));
//                bw.write(ta_1.getText());//escribe el contenido de el area de tecto
//                ta_1.setText("");
                bw.flush(); //flashea, vacia de ram a rom        
                JOptionPane.showMessageDialog(this,
                        "Archivo guardado exitosamente");

            } catch (Exception e) {
                e.printStackTrace();
            }
            try {
                bw.close();
                fw.close();
            } catch (IOException ex) {

            }
            modeloTABLEListar();
        }

    }//GEN-LAST:event_AgregarArchivoBoton1ActionPerformed

    private void TareasCompletasTareasBoton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TareasCompletasTareasBoton1ActionPerformed
        HEADERCOSO.setText("Compartidos");

        modeloTABLEListarcomp();

    }//GEN-LAST:event_TareasCompletasTareasBoton1ActionPerformed

    private void jl_personas1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jl_personas1MouseClicked

    }//GEN-LAST:event_jl_personas1MouseClicked

    private void jl_personas1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jl_personas1KeyPressed

    }//GEN-LAST:event_jl_personas1KeyPressed

    private void GruposBoton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GruposBoton2ActionPerformed
        Grupps.setModal(true);
        Grupps.pack();
        Grupps.setLocationRelativeTo(this);
        Grupps.setVisible(true);
    }//GEN-LAST:event_GruposBoton2ActionPerformed

    private void GruposBoton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GruposBoton3ActionPerformed
        HEADERCOSO.setText("Papelera");
        modeloTABLEListarpapelera();
    }//GEN-LAST:event_GruposBoton3ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        for (int i = 0; i < ArchivosI.size(); i++) {
            if (ArchivosI.get(i).getArch().getName().equals(tabla.getValueAt(tabla.getSelectedRow(), 0))) {
                ArchivosI.get(i).setPapelera("Si");
            }
        }
        modeloTABLEListar();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void BOTONUNIVERSSALMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BOTONUNIVERSSALMouseClicked
        HEADERCOSO.setText("Mi Unidad");
        modeloTABLEListar();
    }//GEN-LAST:event_BOTONUNIVERSSALMouseClicked

    private void jl_personasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jl_personasMouseClicked

    }//GEN-LAST:event_jl_personasMouseClicked

    private void jl_personasKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jl_personasKeyPressed

    }//GEN-LAST:event_jl_personasKeyPressed

    private void jl_Grupos2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jl_Grupos2MouseClicked
        ModelolistIntegrantes(jl_Grupos2.getSelectedValue());
        NombreLista.setText((String) jl_personas.getSelectedValue());
    }//GEN-LAST:event_jl_Grupos2MouseClicked

    private void jl_Grupos2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jl_Grupos2KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jl_Grupos2KeyPressed

    private void TareasEliminarTareasBoton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TareasEliminarTareasBoton2ActionPerformed
        modelocombobox();

        NuevoG.setModal(true);
        NuevoG.pack();
        NuevoG.setLocationRelativeTo(this);
        NuevoG.setVisible(true);

        //modelocombobox();
    }//GEN-LAST:event_TareasEliminarTareasBoton2ActionPerformed

    private void AgregarintegranteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgregarintegranteActionPerformed
        IntegrantesI.add(Main.ListUssers.get(CB_Usuario_Modificar_AT.getSelectedIndex()).getID());
        ModelolistNombre();
                Grupps.setVisible(true);    }//GEN-LAST:event_AgregarintegranteActionPerformed

    private void CB_Usuario_Modificar_ATItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_CB_Usuario_Modificar_ATItemStateChanged

    }//GEN-LAST:event_CB_Usuario_Modificar_ATItemStateChanged

    private void CB_Usuario_Modificar_ATActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CB_Usuario_Modificar_ATActionPerformed

    }//GEN-LAST:event_CB_Usuario_Modificar_ATActionPerformed

    private void TareasEliminarTareasBoton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TareasEliminarTareasBoton4ActionPerformed
        GruposI.add(new Grupo(NombreGrupoTF.getText(), IntegrantesI));
        ModelolistNombre();
        ModelolistNombreELECT();
        Grupps.setVisible(true);    }//GEN-LAST:event_TareasEliminarTareasBoton4ActionPerformed

    private void jl_personas2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jl_personas2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jl_personas2MouseClicked

    private void jl_personas2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jl_personas2KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jl_personas2KeyPressed

    private void jl_Grupos3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jl_Grupos3MouseClicked
//        for (Grupo grupo : GruposI) {
//            if(jl_personas.getSelectedValue())
//            if(jl_Grupos2.getSelectedValue()==grupo){
//                grupo.setIntegrantes(((Grupo)jl_Grupos3.getSelectedValue()).getIntegrantes());
//                
//            }
//        }
        for (Archivo archivo : ArchivosI) {
            if (((tabla.getValueAt(tabla.getSelectedRow(), 0)).toString()).equals(archivo.getArch().getName())) {
                for (Grupo grupo : GruposI) {
                    if (grupo == jl_Grupos3.getSelectedValue()) {
                        archivo.setIdes(((Grupo) jl_Grupos3.getSelectedValue()).getIntegrantes());
                        System.out.println(archivo.getIdes());
                    }
                }
            }

        }


    }//GEN-LAST:event_jl_Grupos3MouseClicked

    private void jl_Grupos3KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jl_Grupos3KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jl_Grupos3KeyPressed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        Grupps1.setModal(true);
        Grupps1.pack();
        Grupps1.setLocationRelativeTo(this);
        Grupps1.setVisible(true);

    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void tablaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaMouseClicked
        tabla.getValueAt(tabla.getSelectedRow(), 0);
        
    }//GEN-LAST:event_tablaMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Drive.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Drive.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Drive.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Drive.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Drive().setVisible(true);
            }
        });
    }

    public void modeloTABLEListar() {
        DefaultTableModel listPersona = (DefaultTableModel) tabla.getModel();
        listPersona.setRowCount(0);

        for (Archivo archivo : ArchivosI) {
            if (archivo.getIdes().get(0) == NewJFrame.Uactual.getID() && archivo.getPapelera().equals("No")) {
                Object[] row = {archivo.getArch().getName(), archivo.getFecha(), NewJFrame.Uactual.getUsuario()};
                listPersona.addRow(row);
            }
        }
        tabla.setModel(listPersona);
    }

    public String fecha() {
        SimpleDateFormat fech = new SimpleDateFormat("dd/MMM/yyyy");
        Date fecha = new Date();
        return fech.format(fecha);
    }

    public void modeloTABLEListarpapelera() {
        DefaultTableModel listPersona = (DefaultTableModel) tabla.getModel();
        listPersona.setRowCount(0);

        for (Archivo archivo : ArchivosI) {
            if (archivo.getIdes().get(0) == NewJFrame.Uactual.getID() && archivo.getPapelera().equals("Si")) {
                Object[] row = {archivo.getArch().getName(), archivo.getFecha(), NewJFrame.Uactual.getUsuario()};
                listPersona.addRow(row);
            }
        }
        tabla.setModel(listPersona);
    }

    public void modelocombobox() {
        CB_Usuario_Modificar_AT.getModel();
        DefaultComboBoxModel m = new DefaultComboBoxModel();
        for (Persona persona : Main.ListUssers) {
            m.addElement(persona);
        }
        CB_Usuario_Modificar_AT.setModel(m);
    }

    public void ModelolistNombre() {
        DefaultListModel modelo
                = (DefaultListModel) jl_Grupos2.getModel();
        modelo.clear();
        for (Grupo gr : GruposI) {
            modelo.addElement(gr);
        }

        jl_Grupos2.setModel(modelo);
        modelocombobox();
    }

    public void ModelolistNombreELECT() {
        DefaultListModel modelo
                = (DefaultListModel) jl_Grupos3.getModel();
        modelo.clear();
        for (Grupo gr : GruposI) {
            modelo.addElement(gr);
        }

        jl_Grupos3.setModel(modelo);
//        modelocombobox();
    }

    public void ModelolistIntegrantes(Object t) {
        DefaultListModel modelo
                = (DefaultListModel) jl_personas.getModel();
        modelo.clear();
        for (Grupo gr : GruposI) {
            if (gr == t) {
                for (Integer integrante : gr.getIntegrantes()) {
                    modelo.addElement(integrante);
                }
            }
        }

        jl_personas.setModel(modelo);
        modelocombobox();
    }

    public void modeloTABLEListarcomp() {
        DefaultTableModel listPersona = (DefaultTableModel) tabla.getModel();
        listPersona.setRowCount(0);
        boolean Coso = false;

        for (Archivo archivo : ArchivosI) {
            if (archivo.getIdes().size() > 0 && archivo.getPapelera().equals("No")) {
                if (archivo.getIdes().size() > 1) {
                    for (Integer ide : archivo.getIdes()) {
                        if (ide == NewJFrame.Uactual.getID()) {
                            Object[] row = {archivo.getArch().getName(), archivo.getFecha(), archivo.getIdes().get(0)};
                            listPersona.addRow(row);
                        }
                    }
                }

            }
        }
        tabla.setModel(listPersona);
    }

    public void recents() {
        DefaultListModel modelo
                = (DefaultListModel) jl_Grupos3.getModel();
        modelo.clear();
        for (Grupo gr : GruposI) {
            modelo.addElement(gr);
        }

        jl_Grupos3.setModel(modelo);
//        modelocombobox();
    }
    private ArrayList<Grupo> GruposI = new ArrayList();
    private ArrayList<Integer> IntegrantesI = new ArrayList();
    private ArrayList<Archivo> ArchivosI = new ArrayList();
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AgregarArchivoBoton1;
    private javax.swing.JButton Agregarintegrante;
    private javax.swing.JLabel BOTONUNIVERSSAL;
    private javax.swing.JComboBox<String> CB_Usuario_Modificar_AT;
    private javax.swing.JButton CrearArchivoBoton1;
    private javax.swing.JButton GruposBoton2;
    private javax.swing.JButton GruposBoton3;
    private javax.swing.JDialog Grupps;
    private javax.swing.JDialog Grupps1;
    private javax.swing.JLabel HEADERCOSO;
    private javax.swing.JLabel HEADERCOSO1;
    private javax.swing.JLabel HEADERCOSO2;
    private javax.swing.JLabel HEADERCOSO3;
    private javax.swing.JLabel HEADERCOSO4;
    private javax.swing.JLabel HEADERCOSO5;
    private javax.swing.JLabel HEADERCOSO6;
    private javax.swing.JLabel HEADERCOSO7;
    private javax.swing.JTextField NombreGrupoTF;
    private javax.swing.JLabel NombreLista;
    private javax.swing.JLabel NombreLista1;
    private javax.swing.JLabel NombreLista2;
    private javax.swing.JLabel Nombre_Usuario_Label;
    private javax.swing.JLabel Nombre_Usuario_Label1;
    private javax.swing.JLabel Nombre_Usuario_Label3;
    private javax.swing.JDialog NuevoG;
    private javax.swing.JPanel PANELLATERAL1;
    private javax.swing.JButton TareasCompletasTareasBoton1;
    private javax.swing.JButton TareasEliminarTareasBoton2;
    private javax.swing.JButton TareasEliminarTareasBoton4;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JList jl_Grupos2;
    private javax.swing.JList jl_Grupos3;
    private javax.swing.JList jl_personas;
    private javax.swing.JList jl_personas1;
    private javax.swing.JList jl_personas2;
    private javax.swing.JTable tabla;
    // End of variables declaration//GEN-END:variables
}
