/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectofinal;

import java.awt.Color;
import java.awt.*;
import java.util.ArrayList;
import javax.swing.*;
import javax.swing.OverlayLayout;
import Clases.Persona;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import DataBase.Dba;
import java.sql.ResultSet;
import java.sql.SQLException;
import proyectofinal.NewJFrame;

public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
        iniciarVA();
        Nombre_Usuario_Label.setText("Bienvenido " + Uactual.getNombre());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        InformacionUsuarioFra = new javax.swing.JDialog();
        jPanel1 = new javax.swing.JPanel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        UsuarioInfo = new javax.swing.JLabel();
        NombreInfo = new javax.swing.JLabel();
        EdadInfo = new javax.swing.JLabel();
        CorreoInfo = new javax.swing.JLabel();
        GeneroInfo = new javax.swing.JLabel();
        IdInfo = new javax.swing.JLabel();
        PanelAdministrador = new javax.swing.JPanel();
        Panel_Lateral = new javax.swing.JPanel();
        FondoCloudy = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        InfoCuenta_AdminTools_MW = new javax.swing.JButton();
        Nombre_Usuario_Label = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        EliminarUsuario_AdminTools_MW = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        CrearUsuario_AdminTools_MW = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        ModificarUsuario_AdminTools_MW = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        ListarUsuarios_AdminTools_MW = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        botonuniversal = new javax.swing.JButton();
        jLabel21 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        Crud_Usuarios_AP = new javax.swing.JPanel();
        ListarPane_AdminTools_MW = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        TablaListar = new javax.swing.JTable();
        EliminarPane_AdminTools_MW = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TABLAELIMINAR = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        ModificarPane_AdminTools_MW = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        CrearUsuarioP_TF_Nombre = new javax.swing.JTextField();
        CrearUsuarioP_TF_Id = new javax.swing.JTextField();
        CrearUsuarioP_TF_Edad = new javax.swing.JTextField();
        CrearUsuarioP_TF_Contraseña = new javax.swing.JTextField();
        CrearUsuarioP_TF_CorreoElec = new javax.swing.JTextField();
        CrearUsuarioP_TF_Usuario = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        CB_Usuario_Modificar_AT = new javax.swing.JComboBox<>();
        CrearPane_AdminTools_MW1 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        CrearUsuarioP_TF_Nombre1 = new javax.swing.JTextField();
        CrearUsuarioP_TF_Id1 = new javax.swing.JTextField();
        CrearUsuarioP_TF_Edad1 = new javax.swing.JTextField();
        CrearUsuarioP_TF_Contraseña1 = new javax.swing.JTextField();
        CrearUsuarioP_TF_CorreoElec1 = new javax.swing.JTextField();
        CrearUsuarioP_TF_Usuario1 = new javax.swing.JTextField();
        jComboBox2 = new javax.swing.JComboBox<>();
        jButton4 = new javax.swing.JButton();

        jPanel1.setBackground(new java.awt.Color(233, 239, 192));

        jLabel24.setFont(new java.awt.Font("Roboto Medium", 1, 14)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(78, 148, 79));
        jLabel24.setText("Usuario");

        jLabel25.setFont(new java.awt.Font("Roboto Medium", 1, 14)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(78, 148, 79));
        jLabel25.setText("Nombre");

        jLabel26.setFont(new java.awt.Font("Roboto Medium", 1, 14)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(78, 148, 79));
        jLabel26.setText("Edad");

        jLabel27.setFont(new java.awt.Font("Roboto Medium", 1, 14)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(78, 148, 79));
        jLabel27.setText("Correo");

        jLabel28.setFont(new java.awt.Font("Roboto Medium", 1, 14)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(78, 148, 79));
        jLabel28.setText("Genero");

        jLabel29.setFont(new java.awt.Font("Roboto Medium", 1, 14)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(78, 148, 79));
        jLabel29.setText("Id");

        UsuarioInfo.setFont(new java.awt.Font("Roboto Medium", 1, 14)); // NOI18N
        UsuarioInfo.setForeground(new java.awt.Color(78, 148, 79));
        UsuarioInfo.setText("Usuario");

        NombreInfo.setFont(new java.awt.Font("Roboto Medium", 1, 14)); // NOI18N
        NombreInfo.setForeground(new java.awt.Color(78, 148, 79));
        NombreInfo.setText("Nombre");

        EdadInfo.setFont(new java.awt.Font("Roboto Medium", 1, 14)); // NOI18N
        EdadInfo.setForeground(new java.awt.Color(78, 148, 79));
        EdadInfo.setText("Edad");

        CorreoInfo.setFont(new java.awt.Font("Roboto Medium", 1, 14)); // NOI18N
        CorreoInfo.setForeground(new java.awt.Color(78, 148, 79));
        CorreoInfo.setText("Correo");

        GeneroInfo.setFont(new java.awt.Font("Roboto Medium", 1, 14)); // NOI18N
        GeneroInfo.setForeground(new java.awt.Color(78, 148, 79));
        GeneroInfo.setText("Genero");

        IdInfo.setFont(new java.awt.Font("Roboto Medium", 1, 14)); // NOI18N
        IdInfo.setForeground(new java.awt.Color(78, 148, 79));
        IdInfo.setText("Id");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel24)
                    .addComponent(jLabel25, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel27, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(EdadInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(IdInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(UsuarioInfo)
                    .addComponent(NombreInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(CorreoInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(GeneroInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(215, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jLabel24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addComponent(jLabel25)
                        .addGap(63, 63, 63)
                        .addComponent(jLabel26)
                        .addGap(63, 63, 63)
                        .addComponent(jLabel27)
                        .addGap(69, 69, 69)
                        .addComponent(jLabel29)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, Short.MAX_VALUE)
                        .addComponent(jLabel28)
                        .addGap(58, 58, 58))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(UsuarioInfo)
                        .addGap(61, 61, 61)
                        .addComponent(NombreInfo)
                        .addGap(63, 63, 63)
                        .addComponent(EdadInfo)
                        .addGap(63, 63, 63)
                        .addComponent(CorreoInfo)
                        .addGap(69, 69, 69)
                        .addComponent(IdInfo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(GeneroInfo)
                        .addGap(20, 20, 20))))
        );

        javax.swing.GroupLayout InformacionUsuarioFraLayout = new javax.swing.GroupLayout(InformacionUsuarioFra.getContentPane());
        InformacionUsuarioFra.getContentPane().setLayout(InformacionUsuarioFraLayout);
        InformacionUsuarioFraLayout.setHorizontalGroup(
            InformacionUsuarioFraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        InformacionUsuarioFraLayout.setVerticalGroup(
            InformacionUsuarioFraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(250, 50));
        setResizable(false);

        PanelAdministrador.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Panel_Lateral.setBackground(new java.awt.Color(233, 239, 192));
        Panel_Lateral.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        FondoCloudy.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/CloudyFormated.png"))); // NOI18N
        Panel_Lateral.add(FondoCloudy, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 40, 860, 510));

        jPanel4.setBackground(new java.awt.Color(180, 225, 151));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        InfoCuenta_AdminTools_MW.setBackground(new java.awt.Color(78, 148, 79));
        InfoCuenta_AdminTools_MW.setFont(new java.awt.Font("Roboto Medium", 1, 14)); // NOI18N
        InfoCuenta_AdminTools_MW.setForeground(new java.awt.Color(233, 239, 192));
        InfoCuenta_AdminTools_MW.setText("Informacion de Cuenta");
        InfoCuenta_AdminTools_MW.setBorder(null);
        InfoCuenta_AdminTools_MW.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InfoCuenta_AdminTools_MWActionPerformed(evt);
            }
        });
        jPanel4.add(InfoCuenta_AdminTools_MW, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 570, 230, 30));

        Nombre_Usuario_Label.setFont(new java.awt.Font("Roboto Medium", 1, 14)); // NOI18N
        Nombre_Usuario_Label.setForeground(new java.awt.Color(78, 148, 79));
        Nombre_Usuario_Label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Nombre_Usuario_Label.setText("Bienvenido Avelardo");
        Nombre_Usuario_Label.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Nombre_Usuario_Label.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel4.add(Nombre_Usuario_Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 230, -1));

        jLabel1.setFont(new java.awt.Font("Roboto Medium", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(78, 148, 79));
        jLabel1.setText("Herrramientas Administrativas");
        jPanel4.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 370, -1, -1));

        jSeparator1.setBackground(new java.awt.Color(78, 148, 79));
        jSeparator1.setForeground(new java.awt.Color(78, 148, 79));
        jSeparator1.setPreferredSize(new java.awt.Dimension(50, 30));
        jPanel4.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 340, 211, 10));

        EliminarUsuario_AdminTools_MW.setBackground(new java.awt.Color(78, 148, 79));
        EliminarUsuario_AdminTools_MW.setFont(new java.awt.Font("Roboto Medium", 1, 14)); // NOI18N
        EliminarUsuario_AdminTools_MW.setForeground(new java.awt.Color(233, 239, 192));
        EliminarUsuario_AdminTools_MW.setText("Eliminar Usuario");
        EliminarUsuario_AdminTools_MW.setBorder(null);
        EliminarUsuario_AdminTools_MW.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        EliminarUsuario_AdminTools_MW.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        EliminarUsuario_AdminTools_MW.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EliminarUsuario_AdminTools_MWActionPerformed(evt);
            }
        });
        jPanel4.add(EliminarUsuario_AdminTools_MW, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 510, 190, 31));

        jPanel2.setBackground(new java.awt.Color(78, 148, 79));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 31, Short.MAX_VALUE)
        );

        jPanel4.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 510, 100, 31));

        CrearUsuario_AdminTools_MW.setBackground(new java.awt.Color(78, 148, 79));
        CrearUsuario_AdminTools_MW.setFont(new java.awt.Font("Roboto Medium", 1, 14)); // NOI18N
        CrearUsuario_AdminTools_MW.setForeground(new java.awt.Color(233, 239, 192));
        CrearUsuario_AdminTools_MW.setText("Crear Usuario");
        CrearUsuario_AdminTools_MW.setBorder(null);
        CrearUsuario_AdminTools_MW.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        CrearUsuario_AdminTools_MW.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        CrearUsuario_AdminTools_MW.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CrearUsuario_AdminTools_MWActionPerformed(evt);
            }
        });
        jPanel4.add(CrearUsuario_AdminTools_MW, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 390, 190, 31));

        jPanel5.setBackground(new java.awt.Color(78, 148, 79));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 31, Short.MAX_VALUE)
        );

        jPanel4.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 390, 100, 31));

        ModificarUsuario_AdminTools_MW.setBackground(new java.awt.Color(78, 148, 79));
        ModificarUsuario_AdminTools_MW.setFont(new java.awt.Font("Roboto Medium", 1, 14)); // NOI18N
        ModificarUsuario_AdminTools_MW.setForeground(new java.awt.Color(233, 239, 192));
        ModificarUsuario_AdminTools_MW.setText("Modificar Usuario");
        ModificarUsuario_AdminTools_MW.setBorder(null);
        ModificarUsuario_AdminTools_MW.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ModificarUsuario_AdminTools_MW.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        ModificarUsuario_AdminTools_MW.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModificarUsuario_AdminTools_MWActionPerformed(evt);
            }
        });
        jPanel4.add(ModificarUsuario_AdminTools_MW, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 470, 190, 31));

        jPanel7.setBackground(new java.awt.Color(78, 148, 79));

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 31, Short.MAX_VALUE)
        );

        jPanel4.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 470, 100, 31));

        ListarUsuarios_AdminTools_MW.setBackground(new java.awt.Color(78, 148, 79));
        ListarUsuarios_AdminTools_MW.setFont(new java.awt.Font("Roboto Medium", 1, 14)); // NOI18N
        ListarUsuarios_AdminTools_MW.setForeground(new java.awt.Color(233, 239, 192));
        ListarUsuarios_AdminTools_MW.setText("Listar Usuarios");
        ListarUsuarios_AdminTools_MW.setBorder(null);
        ListarUsuarios_AdminTools_MW.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ListarUsuarios_AdminTools_MW.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        ListarUsuarios_AdminTools_MW.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ListarUsuarios_AdminTools_MWActionPerformed(evt);
            }
        });
        jPanel4.add(ListarUsuarios_AdminTools_MW, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 430, 190, 31));

        jPanel8.setBackground(new java.awt.Color(78, 148, 79));

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 31, Short.MAX_VALUE)
        );

        jPanel4.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 430, 100, 31));

        botonuniversal.setBackground(new java.awt.Color(78, 148, 79));
        botonuniversal.setFont(new java.awt.Font("Roboto Medium", 1, 24)); // NOI18N
        botonuniversal.setForeground(new java.awt.Color(233, 239, 192));
        botonuniversal.setText("C l o u d y");
        botonuniversal.setBorder(null);
        botonuniversal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonuniversalActionPerformed(evt);
            }
        });
        jPanel4.add(botonuniversal, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 230, 60));

        jLabel21.setBackground(new java.awt.Color(78, 148, 79));
        jLabel21.setFont(new java.awt.Font("Roboto Medium", 1, 12)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(78, 148, 79));
        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/CloudIcon.png"))); // NOI18N
        jLabel21.setText("C l o u d");
        jLabel21.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel4.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, 120, 50));

        jSeparator2.setBackground(new java.awt.Color(78, 148, 79));
        jSeparator2.setForeground(new java.awt.Color(78, 148, 79));
        jSeparator2.setPreferredSize(new java.awt.Dimension(50, 30));
        jPanel4.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 550, 211, 10));

        jLabel22.setBackground(new java.awt.Color(78, 148, 79));
        jLabel22.setFont(new java.awt.Font("Roboto Medium", 1, 12)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(78, 148, 79));
        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/MailIcon.png"))); // NOI18N
        jLabel22.setText("M a i l");
        jLabel22.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel4.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, 130, 50));

        jLabel23.setBackground(new java.awt.Color(78, 148, 79));
        jLabel23.setFont(new java.awt.Font("Roboto Medium", 1, 12)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(78, 148, 79));
        jLabel23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/ToDoIcon.png"))); // NOI18N
        jLabel23.setText("T o - D o");
        jLabel23.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel23.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel23MouseClicked(evt);
            }
        });
        jPanel4.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 130, 40));

        jSeparator3.setBackground(new java.awt.Color(78, 148, 79));
        jSeparator3.setForeground(new java.awt.Color(78, 148, 79));
        jSeparator3.setPreferredSize(new java.awt.Dimension(50, 30));
        jPanel4.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 211, 10));

        Panel_Lateral.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 620));

        Crud_Usuarios_AP.setLayout(new javax.swing.OverlayLayout(Crud_Usuarios_AP));

        ListarPane_AdminTools_MW.setBackground(new java.awt.Color(247, 246, 220));
        ListarPane_AdminTools_MW.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel20.setFont(new java.awt.Font("Roboto Medium", 1, 24)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(78, 148, 79));
        jLabel20.setText("L i s t a r  U s u a r i o");
        ListarPane_AdminTools_MW.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 23, -1, -1));

        TablaListar.setBackground(new java.awt.Color(233, 239, 192));
        TablaListar.setFont(new java.awt.Font("Roboto Medium", 0, 12)); // NOI18N
        TablaListar.setForeground(new java.awt.Color(78, 148, 79));
        TablaListar.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Usuario", "Id"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TablaListar.setGridColor(new java.awt.Color(131, 189, 117));
        jScrollPane2.setViewportView(TablaListar);

        ListarPane_AdminTools_MW.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(33, 81, 734, 420));

        Crud_Usuarios_AP.add(ListarPane_AdminTools_MW);

        EliminarPane_AdminTools_MW.setBackground(new java.awt.Color(247, 246, 220));
        EliminarPane_AdminTools_MW.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel19.setFont(new java.awt.Font("Roboto Medium", 1, 24)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(78, 148, 79));
        jLabel19.setText("E l i m i n a r  U s u a r i o");
        EliminarPane_AdminTools_MW.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 23, -1, -1));

        TABLAELIMINAR.setBackground(new java.awt.Color(233, 239, 192));
        TABLAELIMINAR.setFont(new java.awt.Font("Roboto Medium", 1, 12)); // NOI18N
        TABLAELIMINAR.setForeground(new java.awt.Color(78, 148, 79));
        TABLAELIMINAR.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Usuario", "Id"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TABLAELIMINAR.setGridColor(new java.awt.Color(131, 189, 117));
        jScrollPane1.setViewportView(TABLAELIMINAR);

        EliminarPane_AdminTools_MW.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(33, 81, 734, 219));

        jButton2.setBackground(new java.awt.Color(78, 148, 79));
        jButton2.setFont(new java.awt.Font("Roboto Medium", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(233, 239, 192));
        jButton2.setText("E l i m i n a r  U s u a r i o");
        jButton2.setBorder(null);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        EliminarPane_AdminTools_MW.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 350, 210, 70));

        Crud_Usuarios_AP.add(EliminarPane_AdminTools_MW);

        ModificarPane_AdminTools_MW.setBackground(new java.awt.Color(247, 246, 220));
        ModificarPane_AdminTools_MW.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Roboto Medium", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(78, 148, 79));
        jLabel2.setText("M o d i f i c a r  U s u a r i o");
        ModificarPane_AdminTools_MW.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 23, -1, -1));

        jLabel3.setFont(new java.awt.Font("Roboto Medium", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(78, 148, 79));
        jLabel3.setText("Nombre");
        ModificarPane_AdminTools_MW.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, -1, -1));

        jLabel4.setFont(new java.awt.Font("Roboto Medium", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(78, 148, 79));
        jLabel4.setText("Edad");
        ModificarPane_AdminTools_MW.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, 50, -1));

        jLabel5.setFont(new java.awt.Font("Roboto Medium", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(78, 148, 79));
        jLabel5.setText("Genero");
        ModificarPane_AdminTools_MW.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 260, 50, -1));

        jLabel6.setFont(new java.awt.Font("Roboto Medium", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(78, 148, 79));
        jLabel6.setText("Correo Electronico");
        ModificarPane_AdminTools_MW.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 320, 130, -1));

        jLabel7.setFont(new java.awt.Font("Roboto Medium", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(78, 148, 79));
        jLabel7.setText("Id");
        ModificarPane_AdminTools_MW.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 380, 50, -1));

        jLabel8.setFont(new java.awt.Font("Roboto Medium", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(78, 148, 79));
        jLabel8.setText("Usuario");
        ModificarPane_AdminTools_MW.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 140, 70, -1));

        jLabel9.setFont(new java.awt.Font("Roboto Medium", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(78, 148, 79));
        jLabel9.setText("Contraseña");
        ModificarPane_AdminTools_MW.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 200, 80, -1));

        CrearUsuarioP_TF_Nombre.setBackground(new java.awt.Color(180, 225, 151));
        CrearUsuarioP_TF_Nombre.setFont(new java.awt.Font("Roboto Medium", 1, 14)); // NOI18N
        CrearUsuarioP_TF_Nombre.setForeground(new java.awt.Color(78, 148, 79));
        CrearUsuarioP_TF_Nombre.setBorder(null);
        ModificarPane_AdminTools_MW.add(CrearUsuarioP_TF_Nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, 220, 30));

        CrearUsuarioP_TF_Id.setBackground(new java.awt.Color(180, 225, 151));
        CrearUsuarioP_TF_Id.setFont(new java.awt.Font("Roboto Medium", 1, 14)); // NOI18N
        CrearUsuarioP_TF_Id.setForeground(new java.awt.Color(78, 148, 79));
        CrearUsuarioP_TF_Id.setBorder(null);
        ModificarPane_AdminTools_MW.add(CrearUsuarioP_TF_Id, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 400, 220, 30));

        CrearUsuarioP_TF_Edad.setBackground(new java.awt.Color(180, 225, 151));
        CrearUsuarioP_TF_Edad.setFont(new java.awt.Font("Roboto Medium", 1, 14)); // NOI18N
        CrearUsuarioP_TF_Edad.setForeground(new java.awt.Color(78, 148, 79));
        CrearUsuarioP_TF_Edad.setBorder(null);
        ModificarPane_AdminTools_MW.add(CrearUsuarioP_TF_Edad, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, 220, 30));

        CrearUsuarioP_TF_Contraseña.setBackground(new java.awt.Color(180, 225, 151));
        CrearUsuarioP_TF_Contraseña.setFont(new java.awt.Font("Roboto Medium", 1, 14)); // NOI18N
        CrearUsuarioP_TF_Contraseña.setForeground(new java.awt.Color(78, 148, 79));
        CrearUsuarioP_TF_Contraseña.setBorder(null);
        ModificarPane_AdminTools_MW.add(CrearUsuarioP_TF_Contraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 220, 220, 30));

        CrearUsuarioP_TF_CorreoElec.setBackground(new java.awt.Color(180, 225, 151));
        CrearUsuarioP_TF_CorreoElec.setFont(new java.awt.Font("Roboto Medium", 1, 14)); // NOI18N
        CrearUsuarioP_TF_CorreoElec.setForeground(new java.awt.Color(78, 148, 79));
        CrearUsuarioP_TF_CorreoElec.setBorder(null);
        ModificarPane_AdminTools_MW.add(CrearUsuarioP_TF_CorreoElec, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 340, 220, 30));

        CrearUsuarioP_TF_Usuario.setBackground(new java.awt.Color(180, 225, 151));
        CrearUsuarioP_TF_Usuario.setFont(new java.awt.Font("Roboto Medium", 1, 14)); // NOI18N
        CrearUsuarioP_TF_Usuario.setForeground(new java.awt.Color(78, 148, 79));
        CrearUsuarioP_TF_Usuario.setBorder(null);
        ModificarPane_AdminTools_MW.add(CrearUsuarioP_TF_Usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 160, 220, 30));

        jComboBox1.setBackground(new java.awt.Color(180, 225, 151));
        jComboBox1.setFont(new java.awt.Font("Roboto Medium", 1, 14)); // NOI18N
        jComboBox1.setForeground(new java.awt.Color(78, 148, 79));
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Hombre", "Mujer", "Genero" }));
        jComboBox1.setSelectedIndex(2);
        jComboBox1.setBorder(null);
        ModificarPane_AdminTools_MW.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 280, 220, 30));

        jButton1.setBackground(new java.awt.Color(180, 225, 151));
        jButton1.setFont(new java.awt.Font("Roboto Medium", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(78, 148, 79));
        jButton1.setText("M o d i f i c a r ");
        jButton1.setBorder(null);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        ModificarPane_AdminTools_MW.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 280, 220, 150));

        jLabel18.setFont(new java.awt.Font("Roboto Medium", 1, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(78, 148, 79));
        jLabel18.setText("Usuario");
        ModificarPane_AdminTools_MW.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, 60, -1));

        CB_Usuario_Modificar_AT.setBackground(new java.awt.Color(180, 225, 151));
        CB_Usuario_Modificar_AT.setFont(new java.awt.Font("Roboto Medium", 1, 14)); // NOI18N
        CB_Usuario_Modificar_AT.setForeground(new java.awt.Color(78, 148, 79));
        CB_Usuario_Modificar_AT.setBorder(null);
        CB_Usuario_Modificar_AT.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                CB_Usuario_Modificar_ATItemStateChanged(evt);
            }
        });
        CB_Usuario_Modificar_AT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CB_Usuario_Modificar_ATActionPerformed(evt);
            }
        });
        ModificarPane_AdminTools_MW.add(CB_Usuario_Modificar_AT, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, 220, 30));

        Crud_Usuarios_AP.add(ModificarPane_AdminTools_MW);

        CrearPane_AdminTools_MW1.setBackground(new java.awt.Color(247, 246, 220));
        CrearPane_AdminTools_MW1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setFont(new java.awt.Font("Roboto Medium", 1, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(78, 148, 79));
        jLabel10.setText("C r e a r  U s u a r i o");
        CrearPane_AdminTools_MW1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 23, -1, -1));

        jLabel11.setFont(new java.awt.Font("Roboto Medium", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(78, 148, 79));
        jLabel11.setText("Nombre");
        CrearPane_AdminTools_MW1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, -1, -1));

        jLabel12.setFont(new java.awt.Font("Roboto Medium", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(78, 148, 79));
        jLabel12.setText("Edad");
        CrearPane_AdminTools_MW1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, 50, -1));

        jLabel13.setFont(new java.awt.Font("Roboto Medium", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(78, 148, 79));
        jLabel13.setText("Genero");
        CrearPane_AdminTools_MW1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, 50, -1));

        jLabel14.setFont(new java.awt.Font("Roboto Medium", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(78, 148, 79));
        jLabel14.setText("Correo Electronico");
        CrearPane_AdminTools_MW1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 270, 130, -1));

        jLabel15.setFont(new java.awt.Font("Roboto Medium", 1, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(78, 148, 79));
        jLabel15.setText("Id");
        CrearPane_AdminTools_MW1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 330, 50, -1));

        jLabel16.setFont(new java.awt.Font("Roboto Medium", 1, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(78, 148, 79));
        jLabel16.setText("Usuario");
        CrearPane_AdminTools_MW1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 90, 70, -1));

        jLabel17.setFont(new java.awt.Font("Roboto Medium", 1, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(78, 148, 79));
        jLabel17.setText("Contraseña");
        CrearPane_AdminTools_MW1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 150, 80, -1));

        CrearUsuarioP_TF_Nombre1.setBackground(new java.awt.Color(180, 225, 151));
        CrearUsuarioP_TF_Nombre1.setFont(new java.awt.Font("Roboto Medium", 1, 14)); // NOI18N
        CrearUsuarioP_TF_Nombre1.setForeground(new java.awt.Color(78, 148, 79));
        CrearUsuarioP_TF_Nombre1.setBorder(null);
        CrearPane_AdminTools_MW1.add(CrearUsuarioP_TF_Nombre1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, 220, 30));

        CrearUsuarioP_TF_Id1.setBackground(new java.awt.Color(180, 225, 151));
        CrearUsuarioP_TF_Id1.setFont(new java.awt.Font("Roboto Medium", 1, 14)); // NOI18N
        CrearUsuarioP_TF_Id1.setForeground(new java.awt.Color(78, 148, 79));
        CrearUsuarioP_TF_Id1.setBorder(null);
        CrearPane_AdminTools_MW1.add(CrearUsuarioP_TF_Id1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 350, 220, 30));

        CrearUsuarioP_TF_Edad1.setBackground(new java.awt.Color(180, 225, 151));
        CrearUsuarioP_TF_Edad1.setFont(new java.awt.Font("Roboto Medium", 1, 14)); // NOI18N
        CrearUsuarioP_TF_Edad1.setForeground(new java.awt.Color(78, 148, 79));
        CrearUsuarioP_TF_Edad1.setBorder(null);
        CrearPane_AdminTools_MW1.add(CrearUsuarioP_TF_Edad1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, 220, 30));

        CrearUsuarioP_TF_Contraseña1.setBackground(new java.awt.Color(180, 225, 151));
        CrearUsuarioP_TF_Contraseña1.setFont(new java.awt.Font("Roboto Medium", 1, 14)); // NOI18N
        CrearUsuarioP_TF_Contraseña1.setForeground(new java.awt.Color(78, 148, 79));
        CrearUsuarioP_TF_Contraseña1.setBorder(null);
        CrearPane_AdminTools_MW1.add(CrearUsuarioP_TF_Contraseña1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 170, 220, 30));

        CrearUsuarioP_TF_CorreoElec1.setBackground(new java.awt.Color(180, 225, 151));
        CrearUsuarioP_TF_CorreoElec1.setFont(new java.awt.Font("Roboto Medium", 1, 14)); // NOI18N
        CrearUsuarioP_TF_CorreoElec1.setForeground(new java.awt.Color(78, 148, 79));
        CrearUsuarioP_TF_CorreoElec1.setBorder(null);
        CrearPane_AdminTools_MW1.add(CrearUsuarioP_TF_CorreoElec1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 290, 220, 30));

        CrearUsuarioP_TF_Usuario1.setBackground(new java.awt.Color(180, 225, 151));
        CrearUsuarioP_TF_Usuario1.setFont(new java.awt.Font("Roboto Medium", 1, 14)); // NOI18N
        CrearUsuarioP_TF_Usuario1.setForeground(new java.awt.Color(78, 148, 79));
        CrearUsuarioP_TF_Usuario1.setBorder(null);
        CrearPane_AdminTools_MW1.add(CrearUsuarioP_TF_Usuario1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 110, 220, 30));

        jComboBox2.setBackground(new java.awt.Color(180, 225, 151));
        jComboBox2.setFont(new java.awt.Font("Roboto Medium", 1, 14)); // NOI18N
        jComboBox2.setForeground(new java.awt.Color(78, 148, 79));
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Hombre", "Mujer", "Genero" }));
        jComboBox2.setSelectedIndex(2);
        jComboBox2.setBorder(null);
        CrearPane_AdminTools_MW1.add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, 220, 30));

        jButton4.setBackground(new java.awt.Color(180, 225, 151));
        jButton4.setFont(new java.awt.Font("Roboto Medium", 1, 18)); // NOI18N
        jButton4.setForeground(new java.awt.Color(78, 148, 79));
        jButton4.setText("C r e a r  U s u a r i o");
        jButton4.setBorder(null);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        CrearPane_AdminTools_MW1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 230, 220, 150));

        Crud_Usuarios_AP.add(CrearPane_AdminTools_MW1);

        Panel_Lateral.add(Crud_Usuarios_AP, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 20, 790, 580));

        PanelAdministrador.add(Panel_Lateral, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1080, 620));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelAdministrador, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelAdministrador, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void InfoCuenta_AdminTools_MWActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InfoCuenta_AdminTools_MWActionPerformed
        NombreInfo.setText(Uactual.getNombre());
        UsuarioInfo.setText(Uactual.getUsuario());
        EdadInfo.setText("" + Uactual.getEdad());
        CorreoInfo.setText(Uactual.getCorreo());
        IdInfo.setText("" + Uactual.getID());
        GeneroInfo.setText(Uactual.getGenero());

        InformacionUsuarioFra.setModal(true);
        InformacionUsuarioFra.pack();
        InformacionUsuarioFra.setLocationRelativeTo(this);
        InformacionUsuarioFra.setVisible(true);


    }//GEN-LAST:event_InfoCuenta_AdminTools_MWActionPerformed

    private void CrearUsuario_AdminTools_MWActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CrearUsuario_AdminTools_MWActionPerformed
        CrearPane_AdminTools_MW1.setVisible(true);
        FondoCloudy.setVisible(false);
        Crud_Usuarios_AP.setVisible(true);
        EliminarPane_AdminTools_MW.setVisible(false);
        ListarPane_AdminTools_MW.setVisible((false));
        ModificarPane_AdminTools_MW.setVisible(false);
    }//GEN-LAST:event_CrearUsuario_AdminTools_MWActionPerformed

    private void ModificarUsuario_AdminTools_MWActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModificarUsuario_AdminTools_MWActionPerformed
        ModificarPane_AdminTools_MW.setVisible(true);
        ListarPane_AdminTools_MW.setVisible((false));
        Crud_Usuarios_AP.setVisible(true);
        FondoCloudy.setVisible(false);

        CrearPane_AdminTools_MW1.setVisible(false);
        EliminarPane_AdminTools_MW.setVisible(false);
        modelocombobox();


    }//GEN-LAST:event_ModificarUsuario_AdminTools_MWActionPerformed

    private void EliminarUsuario_AdminTools_MWActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EliminarUsuario_AdminTools_MWActionPerformed
        ModificarPane_AdminTools_MW.setVisible(false);
        Crud_Usuarios_AP.setVisible(true);
        FondoCloudy.setVisible(false);
        EliminarPane_AdminTools_MW.setVisible(true);
        ListarPane_AdminTools_MW.setVisible((false));
        modeloTABLEELIMINAR();
        CrearPane_AdminTools_MW1.setVisible(false);    }//GEN-LAST:event_EliminarUsuario_AdminTools_MWActionPerformed

    private void ListarUsuarios_AdminTools_MWActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ListarUsuarios_AdminTools_MWActionPerformed
        CrearPane_AdminTools_MW1.setVisible(false);
        ListarPane_AdminTools_MW.setVisible((true));
        Crud_Usuarios_AP.setVisible(true);
        FondoCloudy.setVisible(false);
        EliminarPane_AdminTools_MW.setVisible(false);
        modeloTABLEListar();
        modeloTABLEELIMINAR();

        ModificarPane_AdminTools_MW.setVisible(false);    }//GEN-LAST:event_ListarUsuarios_AdminTools_MWActionPerformed

    private void botonuniversalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonuniversalActionPerformed
        TodoVfalse();
        FondoCloudy.setVisible(true);
        Agegar();

    }//GEN-LAST:event_botonuniversalActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        if (((String) jComboBox2.getSelectedItem()).toLowerCase().equals("hombre")) {
            ListUssers.add(new Persona(CrearUsuarioP_TF_Usuario1.getText(),
                    CrearUsuarioP_TF_Contraseña1.getText(),
                    Integer.parseInt(CrearUsuarioP_TF_Edad1.getText()),
                    Integer.parseInt(CrearUsuarioP_TF_Id1.getText()),
                    CrearUsuarioP_TF_Nombre1.getText(),
                    CrearUsuarioP_TF_CorreoElec1.getText(),
                    "Hombre",
                    "No"));
        } else if (((String) jComboBox2.getSelectedItem()).toLowerCase().equals("mujer")) {
            ListUssers.add(new Persona(CrearUsuarioP_TF_Usuario1.getText(),
                    CrearUsuarioP_TF_Contraseña1.getText(),
                    Integer.parseInt(CrearUsuarioP_TF_Edad1.getText()),
                    Integer.parseInt(CrearUsuarioP_TF_Id1.getText()),
                    CrearUsuarioP_TF_Nombre1.getText(),
                    CrearUsuarioP_TF_CorreoElec1.getText(),
                    "Mujer",
                    "No"));
        } else {
            JOptionPane.showMessageDialog(this, "Ingrese un genero valido");
        }

        CrearUsuarioP_TF_Usuario1.setText("");
        CrearUsuarioP_TF_Contraseña1.setText("");
        CrearUsuarioP_TF_Edad1.setText("");
        CrearUsuarioP_TF_Nombre1.setText("");
        CrearUsuarioP_TF_CorreoElec1.setText("");
        CrearUsuarioP_TF_Id1.setText("");
//        System.out.println(ListUssers);

    }//GEN-LAST:event_jButton4ActionPerformed

    private void CB_Usuario_Modificar_ATItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_CB_Usuario_Modificar_ATItemStateChanged

    }//GEN-LAST:event_CB_Usuario_Modificar_ATItemStateChanged

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int index = CB_Usuario_Modificar_AT.getSelectedIndex();

        ListUssers.get(index).setContraseña(CrearUsuarioP_TF_Contraseña.getText());
        ListUssers.get(index).setUsuario(CrearUsuarioP_TF_Usuario.getText());
        ListUssers.get(index).setEdad(Integer.parseInt(CrearUsuarioP_TF_Edad.getText()));
        ListUssers.get(index).setID(Integer.parseInt(CrearUsuarioP_TF_Id.getText()));
        ListUssers.get(index).setNombre(CrearUsuarioP_TF_Nombre.getText());
        ListUssers.get(index).setCorreo(CrearUsuarioP_TF_CorreoElec.getText());

        JOptionPane.showMessageDialog(this, "Usuario cambiado con exito");
        //out.println(ListUssers);

        CrearUsuarioP_TF_Usuario.setText("");
        CrearUsuarioP_TF_Contraseña.setText("");
        CrearUsuarioP_TF_Edad.setText("");
        CrearUsuarioP_TF_Nombre.setText("");
        CrearUsuarioP_TF_CorreoElec.setText("");
        CrearUsuarioP_TF_Id.setText("");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void CB_Usuario_Modificar_ATActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CB_Usuario_Modificar_ATActionPerformed
        CrearUsuarioP_TF_Usuario.setText(((Persona) CB_Usuario_Modificar_AT.getSelectedItem()).getUsuario());
        CrearUsuarioP_TF_Contraseña.setText(((Persona) CB_Usuario_Modificar_AT.getSelectedItem()).getContraseña());
        CrearUsuarioP_TF_Edad.setText("" + ((Persona) CB_Usuario_Modificar_AT.getSelectedItem()).getEdad());
        CrearUsuarioP_TF_Nombre.setText(((Persona) CB_Usuario_Modificar_AT.getSelectedItem()).getNombre());
        CrearUsuarioP_TF_CorreoElec.setText(((Persona) CB_Usuario_Modificar_AT.getSelectedItem()).getCorreo());
        CrearUsuarioP_TF_Id.setText("" + ((Persona) CB_Usuario_Modificar_AT.getSelectedItem()).getID());
    }//GEN-LAST:event_CB_Usuario_Modificar_ATActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        ListUssers.remove(TABLAELIMINAR.getSelectedRow());
        //TABLAELIMINAR.remove(TABLAELIMINAR.getSelectedRow());
        modeloTABLEELIMINAR();
        modeloTABLEListar();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jLabel23MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel23MouseClicked
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ToDo().setVisible(true);
            }
        });
    }//GEN-LAST:event_jLabel23MouseClicked

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    public void iniciarVA() {
        Crud_Usuarios_AP.setVisible(false);
        CrearPane_AdminTools_MW1.setVisible(false);
        ModificarPane_AdminTools_MW.setVisible(false);
    }

    public void TodoVfalse() {
        Crud_Usuarios_AP.setVisible(false);
        CrearPane_AdminTools_MW1.setVisible(false);
        ModificarPane_AdminTools_MW.setVisible(false);
        EliminarPane_AdminTools_MW.setVisible(false);
        ListarPane_AdminTools_MW.setVisible(false);

    }

    public void modelocombobox() {
        CB_Usuario_Modificar_AT.getModel();
        DefaultComboBoxModel m = new DefaultComboBoxModel();
        for (Persona persona : ListUssers) {
            m.addElement(persona);
        }
        CB_Usuario_Modificar_AT.setModel(m);
    }

    public void modeloTABLEListar() {
        DefaultTableModel listPersona = (DefaultTableModel) TablaListar.getModel();
        listPersona.setRowCount(0);

        for (Persona ListUsser : ListUssers) {
            Object[] row = {ListUsser, ListUsser.getUsuario(), ListUsser.getID()};
            listPersona.addRow(row);
        }
        TablaListar.setModel(listPersona);
    }

    public void modeloTABLEELIMINAR() {
        //TABLAELIMINAR.fireTableDataChanged();
        DefaultTableModel listPersona = (DefaultTableModel) TABLAELIMINAR.getModel();
        listPersona.setRowCount(0);
        for (Persona ListUsser : ListUssers) {
            Object[] row = {ListUsser, ListUsser.getUsuario(), ListUsser.getID()};
            listPersona.addRow(row);
        }
        TABLAELIMINAR.setModel(listPersona);
    }

    public void listarDTB() {
        Dba db = new Dba("C:\\Users\\wilme\\Desktop\\Q4-22\\Proyecto Programacion II\\ProyectoFinal\\Usuarios1.accdb");
        db.conectar();
        try {
            db.query.execute("select Usuario,Contraseña,Edad,Nombre,Correo,Genero,Administrador, Id from Usuarios");
            ResultSet rs = db.query.getResultSet();

            while (rs.next()) {
                System.out.println(rs.getString(1)
                        + "--" + rs.getString(2) + "--"
                        + rs.getInt(3) + "--"
                        + rs.getString(4) + "--"
                        + rs.getString(5) + "--"
                        + rs.getString(6) + "--"
                        + rs.getString(7) + "--"
                        + rs.getInt(8));
//                System.out.println(rs.getInt(1) + "--->" + rs.getString(2));
            }
        } catch (SQLException ex) {
            ex.printStackTrace();
        }
        db.desconectar();
    }

    public void Agegar() {

        Dba db = new Dba("C:\\Users\\wilme\\Desktop\\Q4-22\\Proyecto Programacion II\\ProyectoFinal\\Usuarios1.accdb");
        db.conectar();

        try {
            db.query.execute("DELETE FROM Usuarios ");
            for (Persona persona : ListUssers) {
                db.query.execute("INSERT INTO Usuarios"
                        + " (Usuario,Contraseña,Edad,Nombre,Correo,Genero,Administrador,Id)"
                        + " VALUES ('" + persona.getUsuario()
                        + "', '" + persona.getContraseña()
                        + "', '" + persona.getEdad()
                        + "', '" + persona.getNombre()
                        + "', '" + persona.getCorreo()
                        + "', '" + persona.getGenero()
                        + "', '" + persona.getAdministrador()
                        + "', '" + persona.getID()
                        + "')");
                db.commit();
            }

        } catch (SQLException ex) {
            ex.printStackTrace();
        }
        db.desconectar();
    }

    public static ArrayList<Persona> ListUssers = new ArrayList();
    public static Persona Uactual;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> CB_Usuario_Modificar_AT;
    private javax.swing.JLabel CorreoInfo;
    private javax.swing.JPanel CrearPane_AdminTools_MW1;
    private javax.swing.JTextField CrearUsuarioP_TF_Contraseña;
    private javax.swing.JTextField CrearUsuarioP_TF_Contraseña1;
    private javax.swing.JTextField CrearUsuarioP_TF_CorreoElec;
    private javax.swing.JTextField CrearUsuarioP_TF_CorreoElec1;
    private javax.swing.JTextField CrearUsuarioP_TF_Edad;
    private javax.swing.JTextField CrearUsuarioP_TF_Edad1;
    private javax.swing.JTextField CrearUsuarioP_TF_Id;
    private javax.swing.JTextField CrearUsuarioP_TF_Id1;
    private javax.swing.JTextField CrearUsuarioP_TF_Nombre;
    private javax.swing.JTextField CrearUsuarioP_TF_Nombre1;
    private javax.swing.JTextField CrearUsuarioP_TF_Usuario;
    private javax.swing.JTextField CrearUsuarioP_TF_Usuario1;
    private javax.swing.JButton CrearUsuario_AdminTools_MW;
    private javax.swing.JPanel Crud_Usuarios_AP;
    private javax.swing.JLabel EdadInfo;
    private javax.swing.JPanel EliminarPane_AdminTools_MW;
    private javax.swing.JButton EliminarUsuario_AdminTools_MW;
    private javax.swing.JLabel FondoCloudy;
    private javax.swing.JLabel GeneroInfo;
    private javax.swing.JLabel IdInfo;
    private javax.swing.JButton InfoCuenta_AdminTools_MW;
    private javax.swing.JDialog InformacionUsuarioFra;
    private javax.swing.JPanel ListarPane_AdminTools_MW;
    private javax.swing.JButton ListarUsuarios_AdminTools_MW;
    private javax.swing.JPanel ModificarPane_AdminTools_MW;
    private javax.swing.JButton ModificarUsuario_AdminTools_MW;
    private javax.swing.JLabel NombreInfo;
    private javax.swing.JLabel Nombre_Usuario_Label;
    private javax.swing.JPanel PanelAdministrador;
    private javax.swing.JPanel Panel_Lateral;
    private javax.swing.JTable TABLAELIMINAR;
    private javax.swing.JTable TablaListar;
    private javax.swing.JLabel UsuarioInfo;
    private javax.swing.JButton botonuniversal;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    // End of variables declaration//GEN-END:variables
}
