/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectofinal;

import java.awt.Color;
import java.awt.*;
import java.util.ArrayList;
import javax.swing.*;
import javax.swing.OverlayLayout;
import Clases.Persona;
import Clases.DbCon;
import Correo.CorreoCloudy;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import DataBase.Dba;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;

import java.sql.SQLException;

import java.sql.ResultSet;
import proyectofinal.NewJFrame;

public class Main extends javax.swing.JFrame {

    public Main() {
        initComponents();
        iniciarVA();
        Nombre_Usuario_Label.setText("Bienvenido " + NewJFrame.Uactual.getNombre());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        CrearProducto = new javax.swing.JDialog();
        jPanel6 = new javax.swing.JPanel();
        NombreLista1 = new javax.swing.JLabel();
        HEADERCOSO3 = new javax.swing.JLabel();
        Agregarintegrante = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        CrearUsuarioP_TF_Nombre1 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        CrearUsuarioP_TF_Nombre2 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        CrearUsuarioP_TF_Nombre3 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        CrearUsuarioP_TF_Nombre4 = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        CrearUsuarioP_TF_Nombre6 = new javax.swing.JTextField();
        CrearVendedor = new javax.swing.JDialog();
        jPanel9 = new javax.swing.JPanel();
        NombreLista2 = new javax.swing.JLabel();
        HEADERCOSO4 = new javax.swing.JLabel();
        Agregarintegrante1 = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        CrearUsuarioP_TF_Nombre7 = new javax.swing.JTextField();
        CrearCliente = new javax.swing.JDialog();
        jPanel10 = new javax.swing.JPanel();
        NombreLista3 = new javax.swing.JLabel();
        HEADERCOSO5 = new javax.swing.JLabel();
        Agregarintegrante2 = new javax.swing.JButton();
        jLabel27 = new javax.swing.JLabel();
        CrearUsuarioP_TF_Nombre13 = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        CrearUsuarioP_TF_Nombre14 = new javax.swing.JTextField();
        CrearTienda = new javax.swing.JDialog();
        jPanel11 = new javax.swing.JPanel();
        NombreLista4 = new javax.swing.JLabel();
        HEADERCOSO6 = new javax.swing.JLabel();
        Agregarintegrante3 = new javax.swing.JButton();
        jLabel29 = new javax.swing.JLabel();
        CrearUsuarioP_TF_Nombre15 = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        CrearUsuarioP_TF_Nombre16 = new javax.swing.JTextField();
        CrearTiene = new javax.swing.JDialog();
        jPanel12 = new javax.swing.JPanel();
        NombreLista5 = new javax.swing.JLabel();
        HEADERCOSO7 = new javax.swing.JLabel();
        Agregarintegrante4 = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        CrearUsuarioP_TF_Nombre5 = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        CrearUsuarioP_TF_Nombre8 = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        CrearUsuarioP_TF_Nombre9 = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        CrearUsuarioP_TF_Nombre10 = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        CrearUsuarioP_TF_Nombre11 = new javax.swing.JTextField();
        CrearUbicaciones = new javax.swing.JDialog();
        jPanel13 = new javax.swing.JPanel();
        NombreLista6 = new javax.swing.JLabel();
        HEADERCOSO8 = new javax.swing.JLabel();
        Agregarintegrante5 = new javax.swing.JButton();
        jLabel26 = new javax.swing.JLabel();
        CrearUsuarioP_TF_Nombre12 = new javax.swing.JTextField();
        jLabel32 = new javax.swing.JLabel();
        CrearUsuarioP_TF_Nombre18 = new javax.swing.JTextField();
        CrearVende = new javax.swing.JDialog();
        jPanel14 = new javax.swing.JPanel();
        NombreLista7 = new javax.swing.JLabel();
        HEADERCOSO9 = new javax.swing.JLabel();
        Agregarintegrante6 = new javax.swing.JButton();
        jLabel31 = new javax.swing.JLabel();
        CrearUsuarioP_TF_Nombre17 = new javax.swing.JTextField();
        jLabel34 = new javax.swing.JLabel();
        CrearUsuarioP_TF_Nombre20 = new javax.swing.JTextField();
        PanelAdministrador = new javax.swing.JPanel();
        Panel_Lateral = new javax.swing.JPanel();
        FondoCloudy = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        Nombre_Usuario_Label = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        EliminarUsuario_AdminTools_MW = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        CrearUsuario_AdminTools_MW = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        ModificarUsuario_AdminTools_MW = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        ListarUsuarios_AdminTools_MW = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        botonuniversal = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        InfoCuenta_AdminTools_MW1 = new javax.swing.JButton();
        jLabel21 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        Crud_Usuarios_AP = new javax.swing.JPanel();
        ListarPane_AdminTools_MW = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        TablaListar = new javax.swing.JTable();
        CB_Listar = new javax.swing.JComboBox<>();
        EliminarPane_AdminTools_MW = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TABLAELIMINAR = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        CB_Eliminar = new javax.swing.JComboBox<>();
        ModificarPane_AdminTools_MW = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        CrearUsuarioP_TF_Nombre = new javax.swing.JTextField();
        CrearUsuarioP_TF_Id = new javax.swing.JTextField();
        CrearUsuarioP_TF_Edad = new javax.swing.JTextField();
        CrearUsuarioP_TF_Contraseña = new javax.swing.JTextField();
        CrearUsuarioP_TF_CorreoElec = new javax.swing.JTextField();
        CrearUsuarioP_TF_Usuario = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        CB_Usuario_Modificar_AT = new javax.swing.JComboBox<>();
        CrearPane_AdminTools_MW1 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        CB_Crear = new javax.swing.JComboBox<>();

        CrearProducto.setFocusCycleRoot(false);
        CrearProducto.setMinimumSize(new java.awt.Dimension(720, 520));

        jPanel6.setBackground(new java.awt.Color(247, 246, 220));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        NombreLista1.setBackground(new java.awt.Color(247, 246, 220));
        NombreLista1.setFont(new java.awt.Font("Roboto Medium", 1, 18)); // NOI18N
        NombreLista1.setForeground(new java.awt.Color(78, 148, 79));
        jPanel6.add(NombreLista1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        HEADERCOSO3.setFont(new java.awt.Font("Roboto Medium", 1, 30)); // NOI18N
        HEADERCOSO3.setForeground(new java.awt.Color(78, 148, 79));
        HEADERCOSO3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        HEADERCOSO3.setText("Crear Producto");
        HEADERCOSO3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        HEADERCOSO3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel6.add(HEADERCOSO3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 310, 40));

        Agregarintegrante.setBackground(new java.awt.Color(78, 148, 79));
        Agregarintegrante.setFont(new java.awt.Font("Roboto Medium", 1, 14)); // NOI18N
        Agregarintegrante.setForeground(new java.awt.Color(233, 239, 192));
        Agregarintegrante.setText("            Crear");
        Agregarintegrante.setBorder(null);
        Agregarintegrante.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Agregarintegrante.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Agregarintegrante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgregarintegranteActionPerformed(evt);
            }
        });
        jPanel6.add(Agregarintegrante, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 320, 120, 40));

        jLabel11.setFont(new java.awt.Font("Roboto Medium", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(78, 148, 79));
        jLabel11.setText("UPC");
        jPanel6.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, -1, -1));

        CrearUsuarioP_TF_Nombre1.setBackground(new java.awt.Color(180, 225, 151));
        CrearUsuarioP_TF_Nombre1.setFont(new java.awt.Font("Roboto Medium", 1, 14)); // NOI18N
        CrearUsuarioP_TF_Nombre1.setForeground(new java.awt.Color(78, 148, 79));
        CrearUsuarioP_TF_Nombre1.setBorder(null);
        jPanel6.add(CrearUsuarioP_TF_Nombre1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, 220, 30));

        jLabel12.setFont(new java.awt.Font("Roboto Medium", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(78, 148, 79));
        jLabel12.setText("Tamaño");
        jPanel6.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, -1, -1));

        CrearUsuarioP_TF_Nombre2.setBackground(new java.awt.Color(180, 225, 151));
        CrearUsuarioP_TF_Nombre2.setFont(new java.awt.Font("Roboto Medium", 1, 14)); // NOI18N
        CrearUsuarioP_TF_Nombre2.setForeground(new java.awt.Color(78, 148, 79));
        CrearUsuarioP_TF_Nombre2.setBorder(null);
        jPanel6.add(CrearUsuarioP_TF_Nombre2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, 220, 30));

        jLabel13.setFont(new java.awt.Font("Roboto Medium", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(78, 148, 79));
        jLabel13.setText("Nombre");
        jPanel6.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 70, -1, -1));

        CrearUsuarioP_TF_Nombre3.setBackground(new java.awt.Color(180, 225, 151));
        CrearUsuarioP_TF_Nombre3.setFont(new java.awt.Font("Roboto Medium", 1, 14)); // NOI18N
        CrearUsuarioP_TF_Nombre3.setForeground(new java.awt.Color(78, 148, 79));
        CrearUsuarioP_TF_Nombre3.setBorder(null);
        jPanel6.add(CrearUsuarioP_TF_Nombre3, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 100, 220, 30));

        jLabel14.setFont(new java.awt.Font("Roboto Medium", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(78, 148, 79));
        jLabel14.setText("Embalaje");
        jPanel6.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 150, -1, -1));

        CrearUsuarioP_TF_Nombre4.setBackground(new java.awt.Color(180, 225, 151));
        CrearUsuarioP_TF_Nombre4.setFont(new java.awt.Font("Roboto Medium", 1, 14)); // NOI18N
        CrearUsuarioP_TF_Nombre4.setForeground(new java.awt.Color(78, 148, 79));
        CrearUsuarioP_TF_Nombre4.setBorder(null);
        jPanel6.add(CrearUsuarioP_TF_Nombre4, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 180, 220, 30));

        jLabel16.setFont(new java.awt.Font("Roboto Medium", 1, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(78, 148, 79));
        jLabel16.setText("Marca");
        jPanel6.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, -1, -1));

        CrearUsuarioP_TF_Nombre6.setBackground(new java.awt.Color(180, 225, 151));
        CrearUsuarioP_TF_Nombre6.setFont(new java.awt.Font("Roboto Medium", 1, 14)); // NOI18N
        CrearUsuarioP_TF_Nombre6.setForeground(new java.awt.Color(78, 148, 79));
        CrearUsuarioP_TF_Nombre6.setBorder(null);
        CrearUsuarioP_TF_Nombre6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CrearUsuarioP_TF_Nombre6ActionPerformed(evt);
            }
        });
        jPanel6.add(CrearUsuarioP_TF_Nombre6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 260, 220, 30));

        javax.swing.GroupLayout CrearProductoLayout = new javax.swing.GroupLayout(CrearProducto.getContentPane());
        CrearProducto.getContentPane().setLayout(CrearProductoLayout);
        CrearProductoLayout.setHorizontalGroup(
            CrearProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 715, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        CrearProductoLayout.setVerticalGroup(
            CrearProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CrearProductoLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 555, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        CrearVendedor.setMinimumSize(new java.awt.Dimension(720, 520));

        jPanel9.setBackground(new java.awt.Color(247, 246, 220));
        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        NombreLista2.setBackground(new java.awt.Color(247, 246, 220));
        NombreLista2.setFont(new java.awt.Font("Roboto Medium", 1, 18)); // NOI18N
        NombreLista2.setForeground(new java.awt.Color(78, 148, 79));
        jPanel9.add(NombreLista2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        HEADERCOSO4.setFont(new java.awt.Font("Roboto Medium", 1, 30)); // NOI18N
        HEADERCOSO4.setForeground(new java.awt.Color(78, 148, 79));
        HEADERCOSO4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        HEADERCOSO4.setText("Crear Vendedor");
        HEADERCOSO4.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        HEADERCOSO4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel9.add(HEADERCOSO4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 310, 40));

        Agregarintegrante1.setBackground(new java.awt.Color(78, 148, 79));
        Agregarintegrante1.setFont(new java.awt.Font("Roboto Medium", 1, 14)); // NOI18N
        Agregarintegrante1.setForeground(new java.awt.Color(233, 239, 192));
        Agregarintegrante1.setText("            Crear");
        Agregarintegrante1.setBorder(null);
        Agregarintegrante1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Agregarintegrante1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Agregarintegrante1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Agregarintegrante1ActionPerformed(evt);
            }
        });
        jPanel9.add(Agregarintegrante1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 320, 120, 40));

        jLabel17.setFont(new java.awt.Font("Roboto Medium", 1, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(78, 148, 79));
        jLabel17.setText("Nombre");
        jPanel9.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, -1, -1));

        CrearUsuarioP_TF_Nombre7.setBackground(new java.awt.Color(180, 225, 151));
        CrearUsuarioP_TF_Nombre7.setFont(new java.awt.Font("Roboto Medium", 1, 14)); // NOI18N
        CrearUsuarioP_TF_Nombre7.setForeground(new java.awt.Color(78, 148, 79));
        CrearUsuarioP_TF_Nombre7.setBorder(null);
        jPanel9.add(CrearUsuarioP_TF_Nombre7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, 220, 30));

        javax.swing.GroupLayout CrearVendedorLayout = new javax.swing.GroupLayout(CrearVendedor.getContentPane());
        CrearVendedor.getContentPane().setLayout(CrearVendedorLayout);
        CrearVendedorLayout.setHorizontalGroup(
            CrearVendedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CrearVendedorLayout.createSequentialGroup()
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, 715, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 12, Short.MAX_VALUE))
        );
        CrearVendedorLayout.setVerticalGroup(
            CrearVendedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CrearVendedorLayout.createSequentialGroup()
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, 555, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 12, Short.MAX_VALUE))
        );

        CrearCliente.setMinimumSize(new java.awt.Dimension(720, 520));

        jPanel10.setBackground(new java.awt.Color(247, 246, 220));
        jPanel10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        NombreLista3.setBackground(new java.awt.Color(247, 246, 220));
        NombreLista3.setFont(new java.awt.Font("Roboto Medium", 1, 18)); // NOI18N
        NombreLista3.setForeground(new java.awt.Color(78, 148, 79));
        jPanel10.add(NombreLista3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        HEADERCOSO5.setFont(new java.awt.Font("Roboto Medium", 1, 30)); // NOI18N
        HEADERCOSO5.setForeground(new java.awt.Color(78, 148, 79));
        HEADERCOSO5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        HEADERCOSO5.setText("Crear Cliente");
        HEADERCOSO5.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        HEADERCOSO5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel10.add(HEADERCOSO5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 310, 40));

        Agregarintegrante2.setBackground(new java.awt.Color(78, 148, 79));
        Agregarintegrante2.setFont(new java.awt.Font("Roboto Medium", 1, 14)); // NOI18N
        Agregarintegrante2.setForeground(new java.awt.Color(233, 239, 192));
        Agregarintegrante2.setText("            Crear");
        Agregarintegrante2.setBorder(null);
        Agregarintegrante2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Agregarintegrante2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Agregarintegrante2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Agregarintegrante2ActionPerformed(evt);
            }
        });
        jPanel10.add(Agregarintegrante2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 320, 120, 40));

        jLabel27.setFont(new java.awt.Font("Roboto Medium", 1, 14)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(78, 148, 79));
        jLabel27.setText("Nombre");
        jPanel10.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, -1, -1));

        CrearUsuarioP_TF_Nombre13.setBackground(new java.awt.Color(180, 225, 151));
        CrearUsuarioP_TF_Nombre13.setFont(new java.awt.Font("Roboto Medium", 1, 14)); // NOI18N
        CrearUsuarioP_TF_Nombre13.setForeground(new java.awt.Color(78, 148, 79));
        CrearUsuarioP_TF_Nombre13.setBorder(null);
        jPanel10.add(CrearUsuarioP_TF_Nombre13, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, 220, 30));

        jLabel28.setFont(new java.awt.Font("Roboto Medium", 1, 14)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(78, 148, 79));
        jLabel28.setText("Correo Electronico");
        jPanel10.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, -1, -1));

        CrearUsuarioP_TF_Nombre14.setBackground(new java.awt.Color(180, 225, 151));
        CrearUsuarioP_TF_Nombre14.setFont(new java.awt.Font("Roboto Medium", 1, 14)); // NOI18N
        CrearUsuarioP_TF_Nombre14.setForeground(new java.awt.Color(78, 148, 79));
        CrearUsuarioP_TF_Nombre14.setBorder(null);
        jPanel10.add(CrearUsuarioP_TF_Nombre14, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, 220, 30));

        javax.swing.GroupLayout CrearClienteLayout = new javax.swing.GroupLayout(CrearCliente.getContentPane());
        CrearCliente.getContentPane().setLayout(CrearClienteLayout);
        CrearClienteLayout.setHorizontalGroup(
            CrearClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CrearClienteLayout.createSequentialGroup()
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, 715, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 12, Short.MAX_VALUE))
        );
        CrearClienteLayout.setVerticalGroup(
            CrearClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CrearClienteLayout.createSequentialGroup()
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, 555, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 12, Short.MAX_VALUE))
        );

        CrearTienda.setMinimumSize(new java.awt.Dimension(720, 520));

        jPanel11.setBackground(new java.awt.Color(247, 246, 220));
        jPanel11.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        NombreLista4.setBackground(new java.awt.Color(247, 246, 220));
        NombreLista4.setFont(new java.awt.Font("Roboto Medium", 1, 18)); // NOI18N
        NombreLista4.setForeground(new java.awt.Color(78, 148, 79));
        jPanel11.add(NombreLista4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        HEADERCOSO6.setFont(new java.awt.Font("Roboto Medium", 1, 30)); // NOI18N
        HEADERCOSO6.setForeground(new java.awt.Color(78, 148, 79));
        HEADERCOSO6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        HEADERCOSO6.setText("Crear Tienda");
        HEADERCOSO6.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        HEADERCOSO6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel11.add(HEADERCOSO6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 310, 40));

        Agregarintegrante3.setBackground(new java.awt.Color(78, 148, 79));
        Agregarintegrante3.setFont(new java.awt.Font("Roboto Medium", 1, 14)); // NOI18N
        Agregarintegrante3.setForeground(new java.awt.Color(233, 239, 192));
        Agregarintegrante3.setText("            Crear");
        Agregarintegrante3.setBorder(null);
        Agregarintegrante3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Agregarintegrante3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Agregarintegrante3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Agregarintegrante3ActionPerformed(evt);
            }
        });
        jPanel11.add(Agregarintegrante3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 320, 120, 40));

        jLabel29.setFont(new java.awt.Font("Roboto Medium", 1, 14)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(78, 148, 79));
        jLabel29.setText("Nombre tienda");
        jPanel11.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, -1, -1));

        CrearUsuarioP_TF_Nombre15.setBackground(new java.awt.Color(180, 225, 151));
        CrearUsuarioP_TF_Nombre15.setFont(new java.awt.Font("Roboto Medium", 1, 14)); // NOI18N
        CrearUsuarioP_TF_Nombre15.setForeground(new java.awt.Color(78, 148, 79));
        CrearUsuarioP_TF_Nombre15.setBorder(null);
        jPanel11.add(CrearUsuarioP_TF_Nombre15, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, 220, 30));

        jLabel30.setFont(new java.awt.Font("Roboto Medium", 1, 14)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(78, 148, 79));
        jLabel30.setText("Horario");
        jPanel11.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, -1, -1));

        CrearUsuarioP_TF_Nombre16.setBackground(new java.awt.Color(180, 225, 151));
        CrearUsuarioP_TF_Nombre16.setFont(new java.awt.Font("Roboto Medium", 1, 14)); // NOI18N
        CrearUsuarioP_TF_Nombre16.setForeground(new java.awt.Color(78, 148, 79));
        CrearUsuarioP_TF_Nombre16.setBorder(null);
        jPanel11.add(CrearUsuarioP_TF_Nombre16, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, 220, 30));

        javax.swing.GroupLayout CrearTiendaLayout = new javax.swing.GroupLayout(CrearTienda.getContentPane());
        CrearTienda.getContentPane().setLayout(CrearTiendaLayout);
        CrearTiendaLayout.setHorizontalGroup(
            CrearTiendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CrearTiendaLayout.createSequentialGroup()
                .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, 715, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 12, Short.MAX_VALUE))
        );
        CrearTiendaLayout.setVerticalGroup(
            CrearTiendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CrearTiendaLayout.createSequentialGroup()
                .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, 555, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 12, Short.MAX_VALUE))
        );

        CrearTiene.setFocusCycleRoot(false);
        CrearTiene.setMinimumSize(new java.awt.Dimension(720, 520));

        jPanel12.setBackground(new java.awt.Color(247, 246, 220));
        jPanel12.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        NombreLista5.setBackground(new java.awt.Color(247, 246, 220));
        NombreLista5.setFont(new java.awt.Font("Roboto Medium", 1, 18)); // NOI18N
        NombreLista5.setForeground(new java.awt.Color(78, 148, 79));
        jPanel12.add(NombreLista5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        HEADERCOSO7.setFont(new java.awt.Font("Roboto Medium", 1, 30)); // NOI18N
        HEADERCOSO7.setForeground(new java.awt.Color(78, 148, 79));
        HEADERCOSO7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        HEADERCOSO7.setText("Crear Tiene");
        HEADERCOSO7.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        HEADERCOSO7.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel12.add(HEADERCOSO7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 310, 40));

        Agregarintegrante4.setBackground(new java.awt.Color(78, 148, 79));
        Agregarintegrante4.setFont(new java.awt.Font("Roboto Medium", 1, 14)); // NOI18N
        Agregarintegrante4.setForeground(new java.awt.Color(233, 239, 192));
        Agregarintegrante4.setText("            Crear");
        Agregarintegrante4.setBorder(null);
        Agregarintegrante4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Agregarintegrante4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Agregarintegrante4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Agregarintegrante4ActionPerformed(evt);
            }
        });
        jPanel12.add(Agregarintegrante4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 320, 120, 40));

        jLabel15.setFont(new java.awt.Font("Roboto Medium", 1, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(78, 148, 79));
        jLabel15.setText("UPC");
        jPanel12.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, -1, -1));

        CrearUsuarioP_TF_Nombre5.setBackground(new java.awt.Color(180, 225, 151));
        CrearUsuarioP_TF_Nombre5.setFont(new java.awt.Font("Roboto Medium", 1, 14)); // NOI18N
        CrearUsuarioP_TF_Nombre5.setForeground(new java.awt.Color(78, 148, 79));
        CrearUsuarioP_TF_Nombre5.setBorder(null);
        jPanel12.add(CrearUsuarioP_TF_Nombre5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, 220, 30));

        jLabel22.setFont(new java.awt.Font("Roboto Medium", 1, 14)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(78, 148, 79));
        jLabel22.setText("Precio");
        jPanel12.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, -1, -1));

        CrearUsuarioP_TF_Nombre8.setBackground(new java.awt.Color(180, 225, 151));
        CrearUsuarioP_TF_Nombre8.setFont(new java.awt.Font("Roboto Medium", 1, 14)); // NOI18N
        CrearUsuarioP_TF_Nombre8.setForeground(new java.awt.Color(78, 148, 79));
        CrearUsuarioP_TF_Nombre8.setBorder(null);
        jPanel12.add(CrearUsuarioP_TF_Nombre8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, 220, 30));

        jLabel23.setFont(new java.awt.Font("Roboto Medium", 1, 14)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(78, 148, 79));
        jLabel23.setText("Id Tienda");
        jPanel12.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 70, -1, -1));

        CrearUsuarioP_TF_Nombre9.setBackground(new java.awt.Color(180, 225, 151));
        CrearUsuarioP_TF_Nombre9.setFont(new java.awt.Font("Roboto Medium", 1, 14)); // NOI18N
        CrearUsuarioP_TF_Nombre9.setForeground(new java.awt.Color(78, 148, 79));
        CrearUsuarioP_TF_Nombre9.setBorder(null);
        jPanel12.add(CrearUsuarioP_TF_Nombre9, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 100, 220, 30));

        jLabel24.setFont(new java.awt.Font("Roboto Medium", 1, 14)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(78, 148, 79));
        jLabel24.setText("Cantidad");
        jPanel12.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 150, -1, -1));

        CrearUsuarioP_TF_Nombre10.setBackground(new java.awt.Color(180, 225, 151));
        CrearUsuarioP_TF_Nombre10.setFont(new java.awt.Font("Roboto Medium", 1, 14)); // NOI18N
        CrearUsuarioP_TF_Nombre10.setForeground(new java.awt.Color(78, 148, 79));
        CrearUsuarioP_TF_Nombre10.setBorder(null);
        jPanel12.add(CrearUsuarioP_TF_Nombre10, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 180, 220, 30));

        jLabel25.setFont(new java.awt.Font("Roboto Medium", 1, 14)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(78, 148, 79));
        jLabel25.setText("Reorden");
        jPanel12.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, -1, -1));

        CrearUsuarioP_TF_Nombre11.setBackground(new java.awt.Color(180, 225, 151));
        CrearUsuarioP_TF_Nombre11.setFont(new java.awt.Font("Roboto Medium", 1, 14)); // NOI18N
        CrearUsuarioP_TF_Nombre11.setForeground(new java.awt.Color(78, 148, 79));
        CrearUsuarioP_TF_Nombre11.setBorder(null);
        CrearUsuarioP_TF_Nombre11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CrearUsuarioP_TF_Nombre11ActionPerformed(evt);
            }
        });
        jPanel12.add(CrearUsuarioP_TF_Nombre11, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 260, 220, 30));

        javax.swing.GroupLayout CrearTieneLayout = new javax.swing.GroupLayout(CrearTiene.getContentPane());
        CrearTiene.getContentPane().setLayout(CrearTieneLayout);
        CrearTieneLayout.setHorizontalGroup(
            CrearTieneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel12, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 715, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        CrearTieneLayout.setVerticalGroup(
            CrearTieneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CrearTieneLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, 555, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        CrearUbicaciones.setFocusCycleRoot(false);
        CrearUbicaciones.setMinimumSize(new java.awt.Dimension(720, 520));

        jPanel13.setBackground(new java.awt.Color(247, 246, 220));
        jPanel13.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        NombreLista6.setBackground(new java.awt.Color(247, 246, 220));
        NombreLista6.setFont(new java.awt.Font("Roboto Medium", 1, 18)); // NOI18N
        NombreLista6.setForeground(new java.awt.Color(78, 148, 79));
        jPanel13.add(NombreLista6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        HEADERCOSO8.setFont(new java.awt.Font("Roboto Medium", 1, 30)); // NOI18N
        HEADERCOSO8.setForeground(new java.awt.Color(78, 148, 79));
        HEADERCOSO8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        HEADERCOSO8.setText("Crear Ubicaciones");
        HEADERCOSO8.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        HEADERCOSO8.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel13.add(HEADERCOSO8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 310, 40));

        Agregarintegrante5.setBackground(new java.awt.Color(78, 148, 79));
        Agregarintegrante5.setFont(new java.awt.Font("Roboto Medium", 1, 14)); // NOI18N
        Agregarintegrante5.setForeground(new java.awt.Color(233, 239, 192));
        Agregarintegrante5.setText("            Crear");
        Agregarintegrante5.setBorder(null);
        Agregarintegrante5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Agregarintegrante5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Agregarintegrante5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Agregarintegrante5ActionPerformed(evt);
            }
        });
        jPanel13.add(Agregarintegrante5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 320, 120, 40));

        jLabel26.setFont(new java.awt.Font("Roboto Medium", 1, 14)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(78, 148, 79));
        jLabel26.setText("Id Tienda");
        jPanel13.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, -1, -1));

        CrearUsuarioP_TF_Nombre12.setBackground(new java.awt.Color(180, 225, 151));
        CrearUsuarioP_TF_Nombre12.setFont(new java.awt.Font("Roboto Medium", 1, 14)); // NOI18N
        CrearUsuarioP_TF_Nombre12.setForeground(new java.awt.Color(78, 148, 79));
        CrearUsuarioP_TF_Nombre12.setBorder(null);
        jPanel13.add(CrearUsuarioP_TF_Nombre12, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, 220, 30));

        jLabel32.setFont(new java.awt.Font("Roboto Medium", 1, 14)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(78, 148, 79));
        jLabel32.setText("Ubicacion");
        jPanel13.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 70, -1, -1));

        CrearUsuarioP_TF_Nombre18.setBackground(new java.awt.Color(180, 225, 151));
        CrearUsuarioP_TF_Nombre18.setFont(new java.awt.Font("Roboto Medium", 1, 14)); // NOI18N
        CrearUsuarioP_TF_Nombre18.setForeground(new java.awt.Color(78, 148, 79));
        CrearUsuarioP_TF_Nombre18.setBorder(null);
        jPanel13.add(CrearUsuarioP_TF_Nombre18, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 100, 220, 30));

        javax.swing.GroupLayout CrearUbicacionesLayout = new javax.swing.GroupLayout(CrearUbicaciones.getContentPane());
        CrearUbicaciones.getContentPane().setLayout(CrearUbicacionesLayout);
        CrearUbicacionesLayout.setHorizontalGroup(
            CrearUbicacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CrearUbicacionesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, 715, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        CrearUbicacionesLayout.setVerticalGroup(
            CrearUbicacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CrearUbicacionesLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, 555, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        CrearVende.setFocusCycleRoot(false);
        CrearVende.setMinimumSize(new java.awt.Dimension(720, 520));

        jPanel14.setBackground(new java.awt.Color(247, 246, 220));
        jPanel14.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        NombreLista7.setBackground(new java.awt.Color(247, 246, 220));
        NombreLista7.setFont(new java.awt.Font("Roboto Medium", 1, 18)); // NOI18N
        NombreLista7.setForeground(new java.awt.Color(78, 148, 79));
        jPanel14.add(NombreLista7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        HEADERCOSO9.setFont(new java.awt.Font("Roboto Medium", 1, 30)); // NOI18N
        HEADERCOSO9.setForeground(new java.awt.Color(78, 148, 79));
        HEADERCOSO9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        HEADERCOSO9.setText("Crear Vende");
        HEADERCOSO9.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        HEADERCOSO9.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel14.add(HEADERCOSO9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 310, 40));

        Agregarintegrante6.setBackground(new java.awt.Color(78, 148, 79));
        Agregarintegrante6.setFont(new java.awt.Font("Roboto Medium", 1, 14)); // NOI18N
        Agregarintegrante6.setForeground(new java.awt.Color(233, 239, 192));
        Agregarintegrante6.setText("            Crear");
        Agregarintegrante6.setBorder(null);
        Agregarintegrante6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Agregarintegrante6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Agregarintegrante6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Agregarintegrante6ActionPerformed(evt);
            }
        });
        jPanel14.add(Agregarintegrante6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 320, 120, 40));

        jLabel31.setFont(new java.awt.Font("Roboto Medium", 1, 14)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(78, 148, 79));
        jLabel31.setText("UPC");
        jPanel14.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, -1, -1));

        CrearUsuarioP_TF_Nombre17.setBackground(new java.awt.Color(180, 225, 151));
        CrearUsuarioP_TF_Nombre17.setFont(new java.awt.Font("Roboto Medium", 1, 14)); // NOI18N
        CrearUsuarioP_TF_Nombre17.setForeground(new java.awt.Color(78, 148, 79));
        CrearUsuarioP_TF_Nombre17.setBorder(null);
        jPanel14.add(CrearUsuarioP_TF_Nombre17, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, 220, 30));

        jLabel34.setFont(new java.awt.Font("Roboto Medium", 1, 14)); // NOI18N
        jLabel34.setForeground(new java.awt.Color(78, 148, 79));
        jLabel34.setText("Id Vendedor");
        jPanel14.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 70, -1, -1));

        CrearUsuarioP_TF_Nombre20.setBackground(new java.awt.Color(180, 225, 151));
        CrearUsuarioP_TF_Nombre20.setFont(new java.awt.Font("Roboto Medium", 1, 14)); // NOI18N
        CrearUsuarioP_TF_Nombre20.setForeground(new java.awt.Color(78, 148, 79));
        CrearUsuarioP_TF_Nombre20.setBorder(null);
        jPanel14.add(CrearUsuarioP_TF_Nombre20, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 100, 220, 30));

        javax.swing.GroupLayout CrearVendeLayout = new javax.swing.GroupLayout(CrearVende.getContentPane());
        CrearVende.getContentPane().setLayout(CrearVendeLayout);
        CrearVendeLayout.setHorizontalGroup(
            CrearVendeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel14, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 715, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        CrearVendeLayout.setVerticalGroup(
            CrearVendeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CrearVendeLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel14, javax.swing.GroupLayout.PREFERRED_SIZE, 555, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(250, 50));
        setResizable(false);

        PanelAdministrador.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Panel_Lateral.setBackground(new java.awt.Color(233, 239, 192));
        Panel_Lateral.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        FondoCloudy.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/CloudyFormated.png"))); // NOI18N
        Panel_Lateral.add(FondoCloudy, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 40, 860, 510));

        jPanel4.setBackground(new java.awt.Color(180, 225, 151));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Nombre_Usuario_Label.setFont(new java.awt.Font("Roboto Medium", 1, 14)); // NOI18N
        Nombre_Usuario_Label.setForeground(new java.awt.Color(78, 148, 79));
        Nombre_Usuario_Label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Nombre_Usuario_Label.setText("Bienvenido Avelardo");
        Nombre_Usuario_Label.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Nombre_Usuario_Label.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel4.add(Nombre_Usuario_Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 230, -1));

        jLabel1.setFont(new java.awt.Font("Roboto Medium", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(78, 148, 79));
        jLabel1.setText("Herrramientas Administrativas");
        jPanel4.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, -1, -1));

        jSeparator1.setBackground(new java.awt.Color(78, 148, 79));
        jSeparator1.setForeground(new java.awt.Color(78, 148, 79));
        jSeparator1.setPreferredSize(new java.awt.Dimension(50, 30));
        jPanel4.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 211, 10));

        EliminarUsuario_AdminTools_MW.setBackground(new java.awt.Color(78, 148, 79));
        EliminarUsuario_AdminTools_MW.setFont(new java.awt.Font("Roboto Medium", 1, 14)); // NOI18N
        EliminarUsuario_AdminTools_MW.setForeground(new java.awt.Color(233, 239, 192));
        EliminarUsuario_AdminTools_MW.setText("Eliminar ");
        EliminarUsuario_AdminTools_MW.setBorder(null);
        EliminarUsuario_AdminTools_MW.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        EliminarUsuario_AdminTools_MW.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        EliminarUsuario_AdminTools_MW.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EliminarUsuario_AdminTools_MWActionPerformed(evt);
            }
        });
        jPanel4.add(EliminarUsuario_AdminTools_MW, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 280, 190, 31));

        jPanel2.setBackground(new java.awt.Color(78, 148, 79));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 31, Short.MAX_VALUE)
        );

        jPanel4.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, 100, 31));

        CrearUsuario_AdminTools_MW.setBackground(new java.awt.Color(78, 148, 79));
        CrearUsuario_AdminTools_MW.setFont(new java.awt.Font("Roboto Medium", 1, 14)); // NOI18N
        CrearUsuario_AdminTools_MW.setForeground(new java.awt.Color(233, 239, 192));
        CrearUsuario_AdminTools_MW.setText("Crear ");
        CrearUsuario_AdminTools_MW.setBorder(null);
        CrearUsuario_AdminTools_MW.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        CrearUsuario_AdminTools_MW.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        CrearUsuario_AdminTools_MW.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CrearUsuario_AdminTools_MWActionPerformed(evt);
            }
        });
        jPanel4.add(CrearUsuario_AdminTools_MW, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, 190, 31));

        jPanel5.setBackground(new java.awt.Color(78, 148, 79));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 31, Short.MAX_VALUE)
        );

        jPanel4.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 100, 31));

        ModificarUsuario_AdminTools_MW.setBackground(new java.awt.Color(78, 148, 79));
        ModificarUsuario_AdminTools_MW.setFont(new java.awt.Font("Roboto Medium", 1, 14)); // NOI18N
        ModificarUsuario_AdminTools_MW.setForeground(new java.awt.Color(233, 239, 192));
        ModificarUsuario_AdminTools_MW.setText("Modificar ");
        ModificarUsuario_AdminTools_MW.setBorder(null);
        ModificarUsuario_AdminTools_MW.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ModificarUsuario_AdminTools_MW.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        ModificarUsuario_AdminTools_MW.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModificarUsuario_AdminTools_MWActionPerformed(evt);
            }
        });
        jPanel4.add(ModificarUsuario_AdminTools_MW, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 240, 190, 31));

        jPanel7.setBackground(new java.awt.Color(78, 148, 79));

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 31, Short.MAX_VALUE)
        );

        jPanel4.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, 100, 31));

        ListarUsuarios_AdminTools_MW.setBackground(new java.awt.Color(78, 148, 79));
        ListarUsuarios_AdminTools_MW.setFont(new java.awt.Font("Roboto Medium", 1, 14)); // NOI18N
        ListarUsuarios_AdminTools_MW.setForeground(new java.awt.Color(233, 239, 192));
        ListarUsuarios_AdminTools_MW.setText("Listar ");
        ListarUsuarios_AdminTools_MW.setBorder(null);
        ListarUsuarios_AdminTools_MW.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ListarUsuarios_AdminTools_MW.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        ListarUsuarios_AdminTools_MW.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ListarUsuarios_AdminTools_MWActionPerformed(evt);
            }
        });
        jPanel4.add(ListarUsuarios_AdminTools_MW, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, 190, 31));

        jPanel8.setBackground(new java.awt.Color(78, 148, 79));

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 31, Short.MAX_VALUE)
        );

        jPanel4.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 100, 31));

        botonuniversal.setBackground(new java.awt.Color(78, 148, 79));
        botonuniversal.setFont(new java.awt.Font("Roboto Medium", 1, 24)); // NOI18N
        botonuniversal.setForeground(new java.awt.Color(233, 239, 192));
        botonuniversal.setText("Tiendita");
        botonuniversal.setBorder(null);
        botonuniversal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonuniversalActionPerformed(evt);
            }
        });
        jPanel4.add(botonuniversal, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 230, 60));

        jSeparator2.setBackground(new java.awt.Color(78, 148, 79));
        jSeparator2.setForeground(new java.awt.Color(78, 148, 79));
        jSeparator2.setPreferredSize(new java.awt.Dimension(50, 30));
        jPanel4.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 550, 211, 10));

        jSeparator3.setBackground(new java.awt.Color(78, 148, 79));
        jSeparator3.setForeground(new java.awt.Color(78, 148, 79));
        jSeparator3.setPreferredSize(new java.awt.Dimension(50, 30));
        jPanel4.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 211, 10));

        InfoCuenta_AdminTools_MW1.setBackground(new java.awt.Color(78, 148, 79));
        InfoCuenta_AdminTools_MW1.setFont(new java.awt.Font("Roboto Medium", 1, 14)); // NOI18N
        InfoCuenta_AdminTools_MW1.setForeground(new java.awt.Color(233, 239, 192));
        InfoCuenta_AdminTools_MW1.setText("Bitacora");
        InfoCuenta_AdminTools_MW1.setBorder(null);
        InfoCuenta_AdminTools_MW1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InfoCuenta_AdminTools_MW1ActionPerformed(evt);
            }
        });
        jPanel4.add(InfoCuenta_AdminTools_MW1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 570, 230, 30));

        jLabel21.setFont(new java.awt.Font("Roboto Medium", 1, 14)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(78, 148, 79));
        jLabel21.setText("Reportes");
        jPanel4.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 330, -1, -1));

        jSeparator4.setBackground(new java.awt.Color(78, 148, 79));
        jSeparator4.setForeground(new java.awt.Color(78, 148, 79));
        jSeparator4.setPreferredSize(new java.awt.Dimension(50, 30));
        jPanel4.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 320, 211, 10));

        Panel_Lateral.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 620));

        Crud_Usuarios_AP.setLayout(new javax.swing.OverlayLayout(Crud_Usuarios_AP));

        ListarPane_AdminTools_MW.setBackground(new java.awt.Color(247, 246, 220));
        ListarPane_AdminTools_MW.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel20.setFont(new java.awt.Font("Roboto Medium", 1, 24)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(78, 148, 79));
        jLabel20.setText("L i s t a r ");
        ListarPane_AdminTools_MW.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        TablaListar.setBackground(new java.awt.Color(233, 239, 192));
        TablaListar.setFont(new java.awt.Font("Roboto Medium", 0, 12)); // NOI18N
        TablaListar.setForeground(new java.awt.Color(78, 148, 79));
        TablaListar.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Usuario", "Id"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TablaListar.setGridColor(new java.awt.Color(131, 189, 117));
        TablaListar.setSelectionBackground(new java.awt.Color(78, 148, 79));
        jScrollPane2.setViewportView(TablaListar);

        ListarPane_AdminTools_MW.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 734, 420));

        CB_Listar.setBackground(new java.awt.Color(180, 225, 151));
        CB_Listar.setFont(new java.awt.Font("Roboto Medium", 1, 14)); // NOI18N
        CB_Listar.setForeground(new java.awt.Color(78, 148, 79));
        CB_Listar.setBorder(null);
        CB_Listar.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                CB_ListarItemStateChanged(evt);
            }
        });
        CB_Listar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CB_ListarActionPerformed(evt);
            }
        });
        ListarPane_AdminTools_MW.add(CB_Listar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 220, 30));

        Crud_Usuarios_AP.add(ListarPane_AdminTools_MW);

        EliminarPane_AdminTools_MW.setBackground(new java.awt.Color(247, 246, 220));
        EliminarPane_AdminTools_MW.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel19.setFont(new java.awt.Font("Roboto Medium", 1, 24)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(78, 148, 79));
        jLabel19.setText("E l i m i n a r");
        EliminarPane_AdminTools_MW.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 23, -1, -1));

        TABLAELIMINAR.setBackground(new java.awt.Color(233, 239, 192));
        TABLAELIMINAR.setFont(new java.awt.Font("Roboto Medium", 1, 12)); // NOI18N
        TABLAELIMINAR.setForeground(new java.awt.Color(78, 148, 79));
        TABLAELIMINAR.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Usuario", "Id"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TABLAELIMINAR.setGridColor(new java.awt.Color(131, 189, 117));
        TABLAELIMINAR.setSelectionBackground(new java.awt.Color(78, 148, 79));
        jScrollPane1.setViewportView(TABLAELIMINAR);

        EliminarPane_AdminTools_MW.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 734, 219));

        jButton2.setBackground(new java.awt.Color(78, 148, 79));
        jButton2.setFont(new java.awt.Font("Roboto Medium", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(233, 239, 192));
        jButton2.setText("E l i m i n a r  U s u a r i o");
        jButton2.setBorder(null);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        EliminarPane_AdminTools_MW.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 490, 210, 70));

        CB_Eliminar.setBackground(new java.awt.Color(180, 225, 151));
        CB_Eliminar.setFont(new java.awt.Font("Roboto Medium", 1, 14)); // NOI18N
        CB_Eliminar.setForeground(new java.awt.Color(78, 148, 79));
        CB_Eliminar.setBorder(null);
        CB_Eliminar.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                CB_EliminarItemStateChanged(evt);
            }
        });
        CB_Eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CB_EliminarActionPerformed(evt);
            }
        });
        EliminarPane_AdminTools_MW.add(CB_Eliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 220, 30));

        Crud_Usuarios_AP.add(EliminarPane_AdminTools_MW);

        ModificarPane_AdminTools_MW.setBackground(new java.awt.Color(247, 246, 220));
        ModificarPane_AdminTools_MW.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Roboto Medium", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(78, 148, 79));
        jLabel2.setText("M o d i f i c a r  U s u a r i o");
        ModificarPane_AdminTools_MW.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 23, -1, -1));

        jLabel3.setFont(new java.awt.Font("Roboto Medium", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(78, 148, 79));
        jLabel3.setText("Nombre");
        ModificarPane_AdminTools_MW.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, -1, -1));

        jLabel4.setFont(new java.awt.Font("Roboto Medium", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(78, 148, 79));
        jLabel4.setText("Edad");
        ModificarPane_AdminTools_MW.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, 50, -1));

        jLabel5.setFont(new java.awt.Font("Roboto Medium", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(78, 148, 79));
        jLabel5.setText("Genero");
        ModificarPane_AdminTools_MW.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 260, 50, -1));

        jLabel6.setFont(new java.awt.Font("Roboto Medium", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(78, 148, 79));
        jLabel6.setText("Correo Electronico");
        ModificarPane_AdminTools_MW.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 320, 130, -1));

        jLabel7.setFont(new java.awt.Font("Roboto Medium", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(78, 148, 79));
        jLabel7.setText("Id");
        ModificarPane_AdminTools_MW.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 380, 50, -1));

        jLabel8.setFont(new java.awt.Font("Roboto Medium", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(78, 148, 79));
        jLabel8.setText("Usuario");
        ModificarPane_AdminTools_MW.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 140, 70, -1));

        jLabel9.setFont(new java.awt.Font("Roboto Medium", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(78, 148, 79));
        jLabel9.setText("Contraseña");
        ModificarPane_AdminTools_MW.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 200, 80, -1));

        CrearUsuarioP_TF_Nombre.setBackground(new java.awt.Color(180, 225, 151));
        CrearUsuarioP_TF_Nombre.setFont(new java.awt.Font("Roboto Medium", 1, 14)); // NOI18N
        CrearUsuarioP_TF_Nombre.setForeground(new java.awt.Color(78, 148, 79));
        CrearUsuarioP_TF_Nombre.setBorder(null);
        ModificarPane_AdminTools_MW.add(CrearUsuarioP_TF_Nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, 220, 30));

        CrearUsuarioP_TF_Id.setBackground(new java.awt.Color(180, 225, 151));
        CrearUsuarioP_TF_Id.setFont(new java.awt.Font("Roboto Medium", 1, 14)); // NOI18N
        CrearUsuarioP_TF_Id.setForeground(new java.awt.Color(78, 148, 79));
        CrearUsuarioP_TF_Id.setBorder(null);
        ModificarPane_AdminTools_MW.add(CrearUsuarioP_TF_Id, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 400, 220, 30));

        CrearUsuarioP_TF_Edad.setBackground(new java.awt.Color(180, 225, 151));
        CrearUsuarioP_TF_Edad.setFont(new java.awt.Font("Roboto Medium", 1, 14)); // NOI18N
        CrearUsuarioP_TF_Edad.setForeground(new java.awt.Color(78, 148, 79));
        CrearUsuarioP_TF_Edad.setBorder(null);
        ModificarPane_AdminTools_MW.add(CrearUsuarioP_TF_Edad, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, 220, 30));

        CrearUsuarioP_TF_Contraseña.setBackground(new java.awt.Color(180, 225, 151));
        CrearUsuarioP_TF_Contraseña.setFont(new java.awt.Font("Roboto Medium", 1, 14)); // NOI18N
        CrearUsuarioP_TF_Contraseña.setForeground(new java.awt.Color(78, 148, 79));
        CrearUsuarioP_TF_Contraseña.setBorder(null);
        ModificarPane_AdminTools_MW.add(CrearUsuarioP_TF_Contraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 220, 220, 30));

        CrearUsuarioP_TF_CorreoElec.setBackground(new java.awt.Color(180, 225, 151));
        CrearUsuarioP_TF_CorreoElec.setFont(new java.awt.Font("Roboto Medium", 1, 14)); // NOI18N
        CrearUsuarioP_TF_CorreoElec.setForeground(new java.awt.Color(78, 148, 79));
        CrearUsuarioP_TF_CorreoElec.setBorder(null);
        ModificarPane_AdminTools_MW.add(CrearUsuarioP_TF_CorreoElec, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 340, 220, 30));

        CrearUsuarioP_TF_Usuario.setBackground(new java.awt.Color(180, 225, 151));
        CrearUsuarioP_TF_Usuario.setFont(new java.awt.Font("Roboto Medium", 1, 14)); // NOI18N
        CrearUsuarioP_TF_Usuario.setForeground(new java.awt.Color(78, 148, 79));
        CrearUsuarioP_TF_Usuario.setBorder(null);
        ModificarPane_AdminTools_MW.add(CrearUsuarioP_TF_Usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 160, 220, 30));

        jComboBox1.setBackground(new java.awt.Color(180, 225, 151));
        jComboBox1.setFont(new java.awt.Font("Roboto Medium", 1, 14)); // NOI18N
        jComboBox1.setForeground(new java.awt.Color(78, 148, 79));
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Hombre", "Mujer", "Genero" }));
        jComboBox1.setSelectedIndex(2);
        jComboBox1.setBorder(null);
        ModificarPane_AdminTools_MW.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 280, 220, 30));

        jButton1.setBackground(new java.awt.Color(180, 225, 151));
        jButton1.setFont(new java.awt.Font("Roboto Medium", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(78, 148, 79));
        jButton1.setText("M o d i f i c a r ");
        jButton1.setBorder(null);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        ModificarPane_AdminTools_MW.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 280, 220, 150));

        jLabel18.setFont(new java.awt.Font("Roboto Medium", 1, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(78, 148, 79));
        jLabel18.setText("Usuario");
        ModificarPane_AdminTools_MW.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, 60, -1));

        CB_Usuario_Modificar_AT.setBackground(new java.awt.Color(180, 225, 151));
        CB_Usuario_Modificar_AT.setFont(new java.awt.Font("Roboto Medium", 1, 14)); // NOI18N
        CB_Usuario_Modificar_AT.setForeground(new java.awt.Color(78, 148, 79));
        CB_Usuario_Modificar_AT.setBorder(null);
        CB_Usuario_Modificar_AT.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                CB_Usuario_Modificar_ATItemStateChanged(evt);
            }
        });
        CB_Usuario_Modificar_AT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CB_Usuario_Modificar_ATActionPerformed(evt);
            }
        });
        ModificarPane_AdminTools_MW.add(CB_Usuario_Modificar_AT, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, 220, 30));

        Crud_Usuarios_AP.add(ModificarPane_AdminTools_MW);

        CrearPane_AdminTools_MW1.setBackground(new java.awt.Color(247, 246, 220));
        CrearPane_AdminTools_MW1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setFont(new java.awt.Font("Roboto Medium", 1, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(78, 148, 79));
        jLabel10.setText("C r e a r  ");
        CrearPane_AdminTools_MW1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 23, -1, -1));

        jButton4.setBackground(new java.awt.Color(180, 225, 151));
        jButton4.setFont(new java.awt.Font("Roboto Medium", 1, 18)); // NOI18N
        jButton4.setForeground(new java.awt.Color(78, 148, 79));
        jButton4.setText("C r e a r  N u e v o");
        jButton4.setBorder(null);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        CrearPane_AdminTools_MW1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 380, 220, 150));

        CB_Crear.setBackground(new java.awt.Color(180, 225, 151));
        CB_Crear.setFont(new java.awt.Font("Roboto Medium", 1, 14)); // NOI18N
        CB_Crear.setForeground(new java.awt.Color(78, 148, 79));
        CB_Crear.setBorder(null);
        CB_Crear.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                CB_CrearItemStateChanged(evt);
            }
        });
        CB_Crear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CB_CrearActionPerformed(evt);
            }
        });
        CrearPane_AdminTools_MW1.add(CB_Crear, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, 220, 30));

        Crud_Usuarios_AP.add(CrearPane_AdminTools_MW1);

        Panel_Lateral.add(Crud_Usuarios_AP, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 20, 790, 580));

        PanelAdministrador.add(Panel_Lateral, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1080, 620));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelAdministrador, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelAdministrador, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CrearUsuario_AdminTools_MWActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CrearUsuario_AdminTools_MWActionPerformed
        modelocomboboxCREATE();
        CrearPane_AdminTools_MW1.setVisible(true);
        FondoCloudy.setVisible(false);
        Crud_Usuarios_AP.setVisible(true);
        EliminarPane_AdminTools_MW.setVisible(false);
        ListarPane_AdminTools_MW.setVisible((false));
        ModificarPane_AdminTools_MW.setVisible(false);
    }//GEN-LAST:event_CrearUsuario_AdminTools_MWActionPerformed

    private void ModificarUsuario_AdminTools_MWActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModificarUsuario_AdminTools_MWActionPerformed
        ModificarPane_AdminTools_MW.setVisible(true);
        ListarPane_AdminTools_MW.setVisible((false));
        Crud_Usuarios_AP.setVisible(true);
        FondoCloudy.setVisible(false);

        CrearPane_AdminTools_MW1.setVisible(false);
        EliminarPane_AdminTools_MW.setVisible(false);
        modelocombobox();


    }//GEN-LAST:event_ModificarUsuario_AdminTools_MWActionPerformed

    private void EliminarUsuario_AdminTools_MWActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EliminarUsuario_AdminTools_MWActionPerformed
        modelocomboboxEliminar();
        modeloTABLEeliminar();

        ModificarPane_AdminTools_MW.setVisible(false);
        Crud_Usuarios_AP.setVisible(true);
        FondoCloudy.setVisible(false);
        EliminarPane_AdminTools_MW.setVisible(true);
        ListarPane_AdminTools_MW.setVisible((false));
        CrearPane_AdminTools_MW1.setVisible(false);    }//GEN-LAST:event_EliminarUsuario_AdminTools_MWActionPerformed

    private void ListarUsuarios_AdminTools_MWActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ListarUsuarios_AdminTools_MWActionPerformed
        modelocomboboxListar();

        CrearPane_AdminTools_MW1.setVisible(false);
        ListarPane_AdminTools_MW.setVisible((true));
        Crud_Usuarios_AP.setVisible(true);
        FondoCloudy.setVisible(false);
        EliminarPane_AdminTools_MW.setVisible(false);

        modeloTABLEListar();

        ModificarPane_AdminTools_MW.setVisible(false);    }//GEN-LAST:event_ListarUsuarios_AdminTools_MWActionPerformed

    private void botonuniversalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonuniversalActionPerformed
        TodoVfalse();
        FondoCloudy.setVisible(true);
    }//GEN-LAST:event_botonuniversalActionPerformed

    private void CB_Usuario_Modificar_ATItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_CB_Usuario_Modificar_ATItemStateChanged

    }//GEN-LAST:event_CB_Usuario_Modificar_ATItemStateChanged

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int index = CB_Usuario_Modificar_AT.getSelectedIndex();

        ListUssers.get(index).setContraseña(CrearUsuarioP_TF_Contraseña.getText());
        ListUssers.get(index).setUsuario(CrearUsuarioP_TF_Usuario.getText());
        ListUssers.get(index).setEdad(Integer.parseInt(CrearUsuarioP_TF_Edad.getText()));
        ListUssers.get(index).setID(Integer.parseInt(CrearUsuarioP_TF_Id.getText()));
        ListUssers.get(index).setNombre(CrearUsuarioP_TF_Nombre.getText());
        ListUssers.get(index).setCorreo(CrearUsuarioP_TF_CorreoElec.getText());
        JOptionPane.showMessageDialog(this, "Usuario cambiado con exito");
        //out.println(ListUssers);

        CrearUsuarioP_TF_Usuario.setText("");
        CrearUsuarioP_TF_Contraseña.setText("");
        CrearUsuarioP_TF_Edad.setText("");
        CrearUsuarioP_TF_Nombre.setText("");
        CrearUsuarioP_TF_CorreoElec.setText("");
        CrearUsuarioP_TF_Id.setText("");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void CB_Usuario_Modificar_ATActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CB_Usuario_Modificar_ATActionPerformed
        CrearUsuarioP_TF_Usuario.setText(((Persona) CB_Usuario_Modificar_AT.getSelectedItem()).getUsuario());
        CrearUsuarioP_TF_Contraseña.setText(((Persona) CB_Usuario_Modificar_AT.getSelectedItem()).getContraseña());
        CrearUsuarioP_TF_Edad.setText("" + ((Persona) CB_Usuario_Modificar_AT.getSelectedItem()).getEdad());
        CrearUsuarioP_TF_Nombre.setText(((Persona) CB_Usuario_Modificar_AT.getSelectedItem()).getNombre());
        CrearUsuarioP_TF_CorreoElec.setText(((Persona) CB_Usuario_Modificar_AT.getSelectedItem()).getCorreo());
        CrearUsuarioP_TF_Id.setText("" + ((Persona) CB_Usuario_Modificar_AT.getSelectedItem()).getID());
    }//GEN-LAST:event_CB_Usuario_Modificar_ATActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        //deleteElement(String table, Object id)
        System.out.println(TABLAELIMINAR.getColumn(1).toString());
        modeloTABLEeliminar();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void InfoCuenta_AdminTools_MW1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InfoCuenta_AdminTools_MW1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_InfoCuenta_AdminTools_MW1ActionPerformed

    private void CB_ListarItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_CB_ListarItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_CB_ListarItemStateChanged

    private void CB_ListarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CB_ListarActionPerformed
        modeloTABLEListar();
    }//GEN-LAST:event_CB_ListarActionPerformed

    private void CB_EliminarItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_CB_EliminarItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_CB_EliminarItemStateChanged

    private void CB_EliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CB_EliminarActionPerformed
        modeloTABLEeliminar();
    }//GEN-LAST:event_CB_EliminarActionPerformed

    private void CB_CrearItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_CB_CrearItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_CB_CrearItemStateChanged

    private void CB_CrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CB_CrearActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CB_CrearActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {
        String entidad = (String) CB_Crear.getSelectedItem();
        switch (entidad) {
            case "Producto":
                CrearProducto.setVisible(true);
                break;
            case "Vendedor":
                CrearVendedor.setVisible(true);
                break;
            case "Cliente":
                CrearCliente.setVisible(true);
                break;
            case "Factura":
                // Aquí puedes poner el código para manejar la entidad "Factura"
                //crearfa.setVisible(true);
                break;
            case "Tienda":
                CrearTienda.setVisible(true);
                break;
            case "Tiene":
                CrearTiene.setVisible(true);
                break;
            case "Ubicaciones":
                CrearUbicaciones.setVisible(true);
                break;
            case "Vende":
                CrearVende.setVisible(true);
                break;
            case "Detalle_Factura":
                // Aquí puedes poner el código para manejar la entidad "Detalle_Factura"
                break;
            default:
                System.out.println("Entidad no reconocida");
                // Si el valor del String no coincide con ninguna de las opciones anteriores
                break;
        }

    }


    private void AgregarintegranteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgregarintegranteActionPerformed

    }//GEN-LAST:event_AgregarintegranteActionPerformed

    private void CrearUsuarioP_TF_Nombre6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CrearUsuarioP_TF_Nombre6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CrearUsuarioP_TF_Nombre6ActionPerformed

    private void Agregarintegrante1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Agregarintegrante1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Agregarintegrante1ActionPerformed

    private void Agregarintegrante2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Agregarintegrante2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Agregarintegrante2ActionPerformed

    private void Agregarintegrante3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Agregarintegrante3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Agregarintegrante3ActionPerformed

    private void Agregarintegrante4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Agregarintegrante4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Agregarintegrante4ActionPerformed

    private void CrearUsuarioP_TF_Nombre11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CrearUsuarioP_TF_Nombre11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CrearUsuarioP_TF_Nombre11ActionPerformed

    private void Agregarintegrante5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Agregarintegrante5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Agregarintegrante5ActionPerformed

    private void Agregarintegrante6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Agregarintegrante6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Agregarintegrante6ActionPerformed

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    public void iniciarVA() {
        Crud_Usuarios_AP.setVisible(false);
        CrearPane_AdminTools_MW1.setVisible(false);
        ModificarPane_AdminTools_MW.setVisible(false);
    }

    public void TodoVfalse() {
        Crud_Usuarios_AP.setVisible(false);
        CrearPane_AdminTools_MW1.setVisible(false);
        ModificarPane_AdminTools_MW.setVisible(false);
        EliminarPane_AdminTools_MW.setVisible(false);
        ListarPane_AdminTools_MW.setVisible(false);

    }

    public void modelocombobox() {
        CB_Usuario_Modificar_AT.getModel();
        DefaultComboBoxModel m = new DefaultComboBoxModel();
        for (Persona persona : ListUssers) {
            m.addElement(persona);
        }
        CB_Usuario_Modificar_AT.setModel(m);
    }

    //TODO DE LISTAR
    public void modelocomboboxListar() {
        CB_Listar.getModel();
        DefaultComboBoxModel m = new DefaultComboBoxModel();
        for (String entidade : entidades) {
            m.addElement(entidade);
        }
        CB_Listar.setModel(m);
    }

    public void modeloTABLEListar() {
        String entidad = (String) CB_Listar.getSelectedItem();
        DefaultTableModel m = new DefaultTableModel();
        m = (TraerTabla(coso.getTable(entidad)));
        TablaListar.setModel(m);
    }

    //TODO ELIMINAR
    public void modelocomboboxEliminar() {
        CB_Eliminar.getModel();
        DefaultComboBoxModel m = new DefaultComboBoxModel();
        for (String entidade : entidades) {
            m.addElement(entidade);
        }
        CB_Eliminar.setModel(m);
    }

    public void modeloTABLEeliminar() {
        String entidad = (String) CB_Eliminar.getSelectedItem();
        DefaultTableModel m = new DefaultTableModel();
        m = (TraerTabla(coso.getTable(entidad)));
        TABLAELIMINAR.setModel(m);
    }
//TODO DE CREAR

    public void modelocomboboxCREATE() {
        CB_Crear.getModel();
        DefaultComboBoxModel m = new DefaultComboBoxModel();
        for (String entidade : entidadesCrear) {
            m.addElement(entidade);
        }
        CB_Crear.setModel(m);
    }

    public static ArrayList<Persona> ListUssers = new ArrayList();
    public static ArrayList<String> entidades = new ArrayList<String>() {
        {
            add("Producto");
            add("Vendedor");
            add("Cliente");
            add("Factura");
            add("Tiene");
            add("Ubicaciones");
            add("Vende");
            add("Detalle_Factura");
            add("Tienda");
        }
    };

    public static ArrayList<String> entidadesCrear = new ArrayList<String>() {
        {
            add("Producto");
            add("Vendedor");
            add("Cliente");
            add("Factura");
            add("Tiene");
            add("Ubicaciones");
            add("Vende");
            add("Detalle_Factura");
            add("Tienda");
        }
    };

    public DefaultTableModel TraerTabla(ResultSet rs) {
        DefaultTableModel model = new DefaultTableModel();
        try {
            ResultSetMetaData metaData = rs.getMetaData();
            for (int i = 1; i <= metaData.getColumnCount(); i++) {
                model.addColumn(metaData.getColumnName(i));
            }
            while (rs.next()) {
                Object[] row = new Object[metaData.getColumnCount()];
                for (int i = 1; i <= metaData.getColumnCount(); i++) {
                    row[i - 1] = rs.getObject(i);
                }
                model.addRow(row);
            }
            return model;
        } catch (Exception ex) {
            ex.printStackTrace();
        }
        return model;
    }

    DbCon coso = new DbCon("master");
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Agregarintegrante;
    private javax.swing.JButton Agregarintegrante1;
    private javax.swing.JButton Agregarintegrante2;
    private javax.swing.JButton Agregarintegrante3;
    private javax.swing.JButton Agregarintegrante4;
    private javax.swing.JButton Agregarintegrante5;
    private javax.swing.JButton Agregarintegrante6;
    private javax.swing.JComboBox<String> CB_Crear;
    private javax.swing.JComboBox<String> CB_Eliminar;
    private javax.swing.JComboBox<String> CB_Listar;
    private javax.swing.JComboBox<String> CB_Usuario_Modificar_AT;
    private javax.swing.JDialog CrearCliente;
    private javax.swing.JPanel CrearPane_AdminTools_MW1;
    private javax.swing.JDialog CrearProducto;
    private javax.swing.JDialog CrearTienda;
    private javax.swing.JDialog CrearTiene;
    private javax.swing.JDialog CrearUbicaciones;
    private javax.swing.JTextField CrearUsuarioP_TF_Contraseña;
    private javax.swing.JTextField CrearUsuarioP_TF_CorreoElec;
    private javax.swing.JTextField CrearUsuarioP_TF_Edad;
    private javax.swing.JTextField CrearUsuarioP_TF_Id;
    private javax.swing.JTextField CrearUsuarioP_TF_Nombre;
    private javax.swing.JTextField CrearUsuarioP_TF_Nombre1;
    private javax.swing.JTextField CrearUsuarioP_TF_Nombre10;
    private javax.swing.JTextField CrearUsuarioP_TF_Nombre11;
    private javax.swing.JTextField CrearUsuarioP_TF_Nombre12;
    private javax.swing.JTextField CrearUsuarioP_TF_Nombre13;
    private javax.swing.JTextField CrearUsuarioP_TF_Nombre14;
    private javax.swing.JTextField CrearUsuarioP_TF_Nombre15;
    private javax.swing.JTextField CrearUsuarioP_TF_Nombre16;
    private javax.swing.JTextField CrearUsuarioP_TF_Nombre17;
    private javax.swing.JTextField CrearUsuarioP_TF_Nombre18;
    private javax.swing.JTextField CrearUsuarioP_TF_Nombre2;
    private javax.swing.JTextField CrearUsuarioP_TF_Nombre20;
    private javax.swing.JTextField CrearUsuarioP_TF_Nombre3;
    private javax.swing.JTextField CrearUsuarioP_TF_Nombre4;
    private javax.swing.JTextField CrearUsuarioP_TF_Nombre5;
    private javax.swing.JTextField CrearUsuarioP_TF_Nombre6;
    private javax.swing.JTextField CrearUsuarioP_TF_Nombre7;
    private javax.swing.JTextField CrearUsuarioP_TF_Nombre8;
    private javax.swing.JTextField CrearUsuarioP_TF_Nombre9;
    private javax.swing.JTextField CrearUsuarioP_TF_Usuario;
    private javax.swing.JButton CrearUsuario_AdminTools_MW;
    private javax.swing.JDialog CrearVende;
    private javax.swing.JDialog CrearVendedor;
    private javax.swing.JPanel Crud_Usuarios_AP;
    private javax.swing.JPanel EliminarPane_AdminTools_MW;
    private javax.swing.JButton EliminarUsuario_AdminTools_MW;
    private javax.swing.JLabel FondoCloudy;
    private javax.swing.JLabel HEADERCOSO3;
    private javax.swing.JLabel HEADERCOSO4;
    private javax.swing.JLabel HEADERCOSO5;
    private javax.swing.JLabel HEADERCOSO6;
    private javax.swing.JLabel HEADERCOSO7;
    private javax.swing.JLabel HEADERCOSO8;
    private javax.swing.JLabel HEADERCOSO9;
    private javax.swing.JButton InfoCuenta_AdminTools_MW1;
    private javax.swing.JPanel ListarPane_AdminTools_MW;
    private javax.swing.JButton ListarUsuarios_AdminTools_MW;
    private javax.swing.JPanel ModificarPane_AdminTools_MW;
    private javax.swing.JButton ModificarUsuario_AdminTools_MW;
    private javax.swing.JLabel NombreLista1;
    private javax.swing.JLabel NombreLista2;
    private javax.swing.JLabel NombreLista3;
    private javax.swing.JLabel NombreLista4;
    private javax.swing.JLabel NombreLista5;
    private javax.swing.JLabel NombreLista6;
    private javax.swing.JLabel NombreLista7;
    private javax.swing.JLabel Nombre_Usuario_Label;
    private javax.swing.JPanel PanelAdministrador;
    private javax.swing.JPanel Panel_Lateral;
    private javax.swing.JTable TABLAELIMINAR;
    private javax.swing.JTable TablaListar;
    private javax.swing.JButton botonuniversal;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    // End of variables declaration//GEN-END:variables
}
