/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectofinal;

/**
 *
 * @author wilme
 */
public class ToDo extends javax.swing.JFrame {

    /**
     * Creates new form ToDo
     */
    public ToDo() {
        initComponents();
        setLocationRelativeTo(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        PANELLATERAL = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        CrearUsuario_AdminTools_MW = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        ModificarUsuario_AdminTools_MW = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        ListarUsuarios_AdminTools_MW = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        ModificarUsuario_AdminTools_MW1 = new javax.swing.JButton();
        jPanel9 = new javax.swing.JPanel();
        jLabel24 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(233, 239, 192));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(233, 239, 192));

        PANELLATERAL.setBackground(new java.awt.Color(180, 225, 151));
        PANELLATERAL.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel23.setBackground(new java.awt.Color(78, 148, 79));
        jLabel23.setFont(new java.awt.Font("Roboto Medium", 1, 12)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(78, 148, 79));
        jLabel23.setText("L i s t a s");
        jLabel23.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        PANELLATERAL.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 240, 130, 40));

        jScrollPane1.setBackground(new java.awt.Color(131, 189, 117));

        jList1.setBackground(new java.awt.Color(131, 189, 117));
        jList1.setFont(new java.awt.Font("Roboto Medium", 1, 14)); // NOI18N
        jList1.setForeground(new java.awt.Color(78, 148, 79));
        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jList1);

        PANELLATERAL.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 290, 220, 210));

        jSeparator1.setBackground(new java.awt.Color(78, 148, 79));
        jSeparator1.setForeground(new java.awt.Color(78, 148, 79));
        PANELLATERAL.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 280, 220, 20));

        jSeparator2.setBackground(new java.awt.Color(78, 148, 79));
        jSeparator2.setForeground(new java.awt.Color(78, 148, 79));
        PANELLATERAL.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 220, 20));

        CrearUsuario_AdminTools_MW.setBackground(new java.awt.Color(78, 148, 79));
        CrearUsuario_AdminTools_MW.setFont(new java.awt.Font("Roboto Medium", 1, 14)); // NOI18N
        CrearUsuario_AdminTools_MW.setForeground(new java.awt.Color(233, 239, 192));
        CrearUsuario_AdminTools_MW.setText("Crear Lista de Tareas");
        CrearUsuario_AdminTools_MW.setBorder(null);
        CrearUsuario_AdminTools_MW.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        CrearUsuario_AdminTools_MW.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        CrearUsuario_AdminTools_MW.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CrearUsuario_AdminTools_MWActionPerformed(evt);
            }
        });
        PANELLATERAL.add(CrearUsuario_AdminTools_MW, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 190, 31));

        jPanel5.setBackground(new java.awt.Color(78, 148, 79));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 31, Short.MAX_VALUE)
        );

        PANELLATERAL.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 100, 31));

        ModificarUsuario_AdminTools_MW.setBackground(new java.awt.Color(78, 148, 79));
        ModificarUsuario_AdminTools_MW.setFont(new java.awt.Font("Roboto Medium", 1, 14)); // NOI18N
        ModificarUsuario_AdminTools_MW.setForeground(new java.awt.Color(233, 239, 192));
        ModificarUsuario_AdminTools_MW.setText("Mi dia");
        ModificarUsuario_AdminTools_MW.setBorder(null);
        ModificarUsuario_AdminTools_MW.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ModificarUsuario_AdminTools_MW.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        ModificarUsuario_AdminTools_MW.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModificarUsuario_AdminTools_MWActionPerformed(evt);
            }
        });
        PANELLATERAL.add(ModificarUsuario_AdminTools_MW, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, 190, 31));

        jPanel7.setBackground(new java.awt.Color(78, 148, 79));

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 31, Short.MAX_VALUE)
        );

        PANELLATERAL.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, 100, 31));

        ListarUsuarios_AdminTools_MW.setBackground(new java.awt.Color(78, 148, 79));
        ListarUsuarios_AdminTools_MW.setFont(new java.awt.Font("Roboto Medium", 1, 14)); // NOI18N
        ListarUsuarios_AdminTools_MW.setForeground(new java.awt.Color(233, 239, 192));
        ListarUsuarios_AdminTools_MW.setText("Agregar Tarea");
        ListarUsuarios_AdminTools_MW.setBorder(null);
        ListarUsuarios_AdminTools_MW.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ListarUsuarios_AdminTools_MW.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        ListarUsuarios_AdminTools_MW.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ListarUsuarios_AdminTools_MWActionPerformed(evt);
            }
        });
        PANELLATERAL.add(ListarUsuarios_AdminTools_MW, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 190, 31));

        jPanel8.setBackground(new java.awt.Color(78, 148, 79));

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 31, Short.MAX_VALUE)
        );

        PANELLATERAL.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 100, 31));

        ModificarUsuario_AdminTools_MW1.setBackground(new java.awt.Color(78, 148, 79));
        ModificarUsuario_AdminTools_MW1.setFont(new java.awt.Font("Roboto Medium", 1, 14)); // NOI18N
        ModificarUsuario_AdminTools_MW1.setForeground(new java.awt.Color(233, 239, 192));
        ModificarUsuario_AdminTools_MW1.setText("Tareas Completadas");
        ModificarUsuario_AdminTools_MW1.setBorder(null);
        ModificarUsuario_AdminTools_MW1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ModificarUsuario_AdminTools_MW1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        ModificarUsuario_AdminTools_MW1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModificarUsuario_AdminTools_MW1ActionPerformed(evt);
            }
        });
        PANELLATERAL.add(ModificarUsuario_AdminTools_MW1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 540, 190, 31));

        jPanel9.setBackground(new java.awt.Color(78, 148, 79));

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 31, Short.MAX_VALUE)
        );

        PANELLATERAL.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 540, 100, 31));

        jLabel24.setBackground(new java.awt.Color(78, 148, 79));
        jLabel24.setFont(new java.awt.Font("Roboto Medium", 1, 12)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(78, 148, 79));
        jLabel24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/ToDoIcon.png"))); // NOI18N
        jLabel24.setText("T o - D o");
        jLabel24.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        PANELLATERAL.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 130, 40));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(PANELLATERAL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 825, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PANELLATERAL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1030, 610));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CrearUsuario_AdminTools_MWActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CrearUsuario_AdminTools_MWActionPerformed
       
    }//GEN-LAST:event_CrearUsuario_AdminTools_MWActionPerformed

    private void ModificarUsuario_AdminTools_MWActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModificarUsuario_AdminTools_MWActionPerformed

    }//GEN-LAST:event_ModificarUsuario_AdminTools_MWActionPerformed

    private void ListarUsuarios_AdminTools_MWActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ListarUsuarios_AdminTools_MWActionPerformed

    }//GEN-LAST:event_ListarUsuarios_AdminTools_MWActionPerformed

    private void ModificarUsuario_AdminTools_MW1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModificarUsuario_AdminTools_MW1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ModificarUsuario_AdminTools_MW1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ToDo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ToDo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ToDo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ToDo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ToDo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CrearUsuario_AdminTools_MW;
    private javax.swing.JButton ListarUsuarios_AdminTools_MW;
    private javax.swing.JButton ModificarUsuario_AdminTools_MW;
    private javax.swing.JButton ModificarUsuario_AdminTools_MW1;
    private javax.swing.JPanel PANELLATERAL;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JList<String> jList1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    // End of variables declaration//GEN-END:variables
}
