/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Correo;

import Clases.Persona;
import DataBase.Dba;
import com.healthmarketscience.jackcess.PropertyMap;
import java.awt.Color;
import java.awt.Font;
import java.io.File;
import java.io.FileOutputStream;
import java.io.InputStream;
import java.security.MessageDigest;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Properties;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.activation.DataHandler;
import javax.activation.FileDataSource;
import javax.mail.BodyPart;
import javax.mail.Folder;
import javax.mail.Message;
import javax.mail.MessagingException;
import javax.mail.Multipart;
import javax.mail.Part;
import javax.mail.PasswordAuthentication;
import javax.mail.Session;
import javax.mail.Store;
import javax.mail.internet.InternetAddress;
import javax.mail.internet.MimeBodyPart;
import javax.mail.internet.MimeMultipart;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import proyectofinal.NewJFrame;
import proyectofinal.Main;

/**
 *
 * @author Usuario
 */
public class CorreoCloudy extends javax.swing.JFrame {

    public CorreoCloudy(int indexCuenta) {
        initComponents();
        pack();
        setLocationRelativeTo(null);
        props = new Properties();
        props.setProperty("mail.imap.starttls.enable", "false");
        props.setProperty("mail.imap.socketFactory.class", "javax.net.ssl.SSLSocketFactory");
        props.setProperty("mail.imap.socketFactory.fallback", "false");
        props.setProperty("mail.imap.port", "993");
        props.setProperty("mail.imap.socketFactory.port", "993");
        Cargarcoruss();
        CargarDrafts();        
        Cargarcontac();


        Usser = NewJFrame.Uactual.getCorreo();
        Contraseña = JOptionPane.showInputDialog(this, "Ingrese la contraseña de su correo");

        Conectandoconlosdiosesdelasmatematicas();
        Bandejas = new Bandejas();
        Bandejas.setEliminados(ElementoEliminados);
        Bandejas.setEnviados(ElementosEnviados);
        Bandejas.setSpam(MierdaSpam);
        Bandejas.setInbox(BandejadeEntrada);

        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        EnviarCuadrito = new javax.swing.JDialog();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        Body = new javax.swing.JTextArea();
        jPanel3 = new javax.swing.JPanel();
        Aquienenvia = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        Subject = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        send = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        GuardarDraft = new javax.swing.JLabel();
        AgregarCuadrito = new javax.swing.JDialog();
        jPanel8 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        encabezadosapo = new javax.swing.JLabel();
        Contactos = new javax.swing.JDialog();
        jPanel11 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        coso = new javax.swing.JLabel();
        CuadritoDrafts = new javax.swing.JDialog();
        jPanel13 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jList2 = new javax.swing.JList<>();
        headercosa = new javax.swing.JLabel();
        panel = new javax.swing.JPanel();
        panel1 = new javax.swing.JPanel();
        enviarcorreopanel = new javax.swing.JPanel();
        jlabel2 = new javax.swing.JLabel();
        Inboxpane = new javax.swing.JPanel();
        jlable8 = new javax.swing.JLabel();
        paneenviadosjpanel = new javax.swing.JPanel();
        jlabel8 = new javax.swing.JLabel();
        PanelMierdaSpam = new javax.swing.JPanel();
        jlabel9 = new javax.swing.JLabel();
        panel_eliminados = new javax.swing.JPanel();
        label_eliminados = new javax.swing.JLabel();
        Panelcosojpane = new javax.swing.JPanel();
        label10 = new javax.swing.JLabel();
        Contactpane = new javax.swing.JPanel();
        addcont = new javax.swing.JLabel();
        drafts = new javax.swing.JPanel();
        draftscoso = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        CONTENIDOCORREO = new javax.swing.JEditorPane();
        INBOX = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        Tablain = new javax.swing.JTable();
        jPanel15 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jPanel16 = new javax.swing.JPanel();
        jlabel52 = new javax.swing.JLabel();
        jPanel17 = new javax.swing.JPanel();
        SUBJECTLABEL = new javax.swing.JLabel();
        jPanel18 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jPanel19 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        DELETE = new javax.swing.JPanel();
        jScrollPane6 = new javax.swing.JScrollPane();
        DELETED = new javax.swing.JTable();
        jPanel20 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        SWPAM = new javax.swing.JPanel();
        jScrollPane7 = new javax.swing.JScrollPane();
        SABLASPAM = new javax.swing.JTable();
        jPanel21 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        sent = new javax.swing.JPanel();
        jScrollPane8 = new javax.swing.JScrollPane();
        enviaditos = new javax.swing.JTable();
        jPanel22 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();

        jPanel1.setBackground(new java.awt.Color(247, 246, 220));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(233, 239, 192));

        jScrollPane3.setBorder(null);

        Body.setBackground(new java.awt.Color(233, 239, 192));
        Body.setColumns(20);
        Body.setFont(new java.awt.Font("Roboto Medium", 1, 12)); // NOI18N
        Body.setForeground(new java.awt.Color(78, 148, 79));
        Body.setRows(5);
        jScrollPane3.setViewportView(Body);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 478, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 490, 340));

        jPanel3.setBackground(new java.awt.Color(78, 148, 79));
        jPanel3.setForeground(new java.awt.Color(233, 239, 192));

        Aquienenvia.setBackground(new java.awt.Color(78, 148, 79));
        Aquienenvia.setFont(new java.awt.Font("Roboto Medium", 1, 14)); // NOI18N
        Aquienenvia.setForeground(new java.awt.Color(233, 239, 192));
        Aquienenvia.setText("Ingrese el Destino del Correo");
        Aquienenvia.setBorder(null);
        Aquienenvia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AquienenviaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Aquienenvia, javax.swing.GroupLayout.DEFAULT_SIZE, 358, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Aquienenvia, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 30, 370, 30));

        jPanel4.setBackground(new java.awt.Color(78, 148, 79));
        jPanel4.setForeground(new java.awt.Color(233, 239, 192));

        Subject.setBackground(new java.awt.Color(78, 148, 79));
        Subject.setFont(new java.awt.Font("Roboto Medium", 1, 14)); // NOI18N
        Subject.setForeground(new java.awt.Color(233, 239, 192));
        Subject.setText("Ingrese el Asunto del Correo");
        Subject.setBorder(null);
        Subject.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubjectActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Subject, javax.swing.GroupLayout.DEFAULT_SIZE, 358, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Subject, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 70, 370, 30));

        jPanel5.setBackground(new java.awt.Color(78, 148, 79));

        send.setFont(new java.awt.Font("Roboto Medium", 1, 18)); // NOI18N
        send.setForeground(new java.awt.Color(233, 239, 192));
        send.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        send.setText("Enviar");
        send.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sendMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(send, javax.swing.GroupLayout.DEFAULT_SIZE, 106, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(send, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 480, 130, 40));

        jPanel6.setBackground(new java.awt.Color(78, 148, 79));
        jPanel6.setForeground(new java.awt.Color(255, 255, 255));

        GuardarDraft.setFont(new java.awt.Font("Roboto Medium", 1, 18)); // NOI18N
        GuardarDraft.setForeground(new java.awt.Color(233, 239, 192));
        GuardarDraft.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        GuardarDraft.setText("Guardar Borrador");
        GuardarDraft.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                GuardarDraftMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(GuardarDraft, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(GuardarDraft, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 480, -1, 40));

        javax.swing.GroupLayout EnviarCuadritoLayout = new javax.swing.GroupLayout(EnviarCuadrito.getContentPane());
        EnviarCuadrito.getContentPane().setLayout(EnviarCuadritoLayout);
        EnviarCuadritoLayout.setHorizontalGroup(
            EnviarCuadritoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 511, Short.MAX_VALUE)
        );
        EnviarCuadritoLayout.setVerticalGroup(
            EnviarCuadritoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EnviarCuadritoLayout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 537, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel8.setBackground(new java.awt.Color(247, 246, 220));
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel10.setBackground(new java.awt.Color(78, 148, 79));
        jPanel10.setForeground(new java.awt.Color(233, 239, 192));

        jLabel6.setFont(new java.awt.Font("Roboto Medium", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(233, 239, 192));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Agregar");
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 76, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        jPanel8.add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 160, -1, 40));

        jComboBox1.setBackground(new java.awt.Color(180, 225, 151));
        jComboBox1.setFont(new java.awt.Font("Roboto Medium", 1, 12)); // NOI18N
        jComboBox1.setForeground(new java.awt.Color(78, 148, 79));
        jPanel8.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, 160, 30));

        encabezadosapo.setFont(new java.awt.Font("Roboto Medium", 1, 36)); // NOI18N
        encabezadosapo.setForeground(new java.awt.Color(78, 148, 79));
        encabezadosapo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        encabezadosapo.setText("Agregar");
        encabezadosapo.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        encabezadosapo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel8.add(encabezadosapo, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, -1, 40));

        javax.swing.GroupLayout AgregarCuadritoLayout = new javax.swing.GroupLayout(AgregarCuadrito.getContentPane());
        AgregarCuadrito.getContentPane().setLayout(AgregarCuadritoLayout);
        AgregarCuadritoLayout.setHorizontalGroup(
            AgregarCuadritoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        AgregarCuadritoLayout.setVerticalGroup(
            AgregarCuadritoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, 238, Short.MAX_VALUE)
        );

        jPanel11.setBackground(new java.awt.Color(233, 239, 192));

        jScrollPane4.setBorder(null);

        jList1.setBackground(new java.awt.Color(131, 189, 117));
        jList1.setFont(new java.awt.Font("Roboto Medium", 1, 18)); // NOI18N
        jList1.setForeground(new java.awt.Color(78, 148, 79));
        jList1.setModel(new DefaultListModel());
        jScrollPane4.setViewportView(jList1);

        coso.setFont(new java.awt.Font("Roboto Medium", 1, 36)); // NOI18N
        coso.setForeground(new java.awt.Color(78, 148, 79));
        coso.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        coso.setText("Contactos");
        coso.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        coso.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(coso)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(coso, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 39, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout ContactosLayout = new javax.swing.GroupLayout(Contactos.getContentPane());
        Contactos.getContentPane().setLayout(ContactosLayout);
        ContactosLayout.setHorizontalGroup(
            ContactosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        ContactosLayout.setVerticalGroup(
            ContactosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel13.setBackground(new java.awt.Color(233, 239, 192));

        jScrollPane5.setBorder(null);

        jList2.setBackground(new java.awt.Color(131, 189, 117));
        jList2.setFont(new java.awt.Font("Roboto Medium", 1, 18)); // NOI18N
        jList2.setForeground(new java.awt.Color(78, 148, 79));
        jList2.setModel(new DefaultListModel());
        jList2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jList2MouseClicked(evt);
            }
        });
        jScrollPane5.setViewportView(jList2);

        headercosa.setFont(new java.awt.Font("Roboto Medium", 1, 36)); // NOI18N
        headercosa.setForeground(new java.awt.Color(78, 148, 79));
        headercosa.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        headercosa.setText("Borradores");
        headercosa.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        headercosa.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(headercosa)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(42, Short.MAX_VALUE))
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addComponent(headercosa, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout CuadritoDraftsLayout = new javax.swing.GroupLayout(CuadritoDrafts.getContentPane());
        CuadritoDrafts.getContentPane().setLayout(CuadritoDraftsLayout);
        CuadritoDraftsLayout.setHorizontalGroup(
            CuadritoDraftsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        CuadritoDraftsLayout.setVerticalGroup(
            CuadritoDraftsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setResizable(false);

        panel.setBackground(new java.awt.Color(233, 239, 192));
        panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panel1.setBackground(new java.awt.Color(180, 225, 151));
        panel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        enviarcorreopanel.setBackground(new java.awt.Color(78, 148, 79));

        jlabel2.setFont(new java.awt.Font("Roboto Medium", 1, 18)); // NOI18N
        jlabel2.setForeground(new java.awt.Color(233, 239, 192));
        jlabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlabel2.setText("Enviar Correo");
        jlabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlabel2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jlabel2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jlabel2MouseExited(evt);
            }
        });

        javax.swing.GroupLayout enviarcorreopanelLayout = new javax.swing.GroupLayout(enviarcorreopanel);
        enviarcorreopanel.setLayout(enviarcorreopanelLayout);
        enviarcorreopanelLayout.setHorizontalGroup(
            enviarcorreopanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(enviarcorreopanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        enviarcorreopanelLayout.setVerticalGroup(
            enviarcorreopanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jlabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
        );

        panel1.add(enviarcorreopanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 91, 190, -1));

        Inboxpane.setBackground(new java.awt.Color(78, 148, 79));

        jlable8.setFont(new java.awt.Font("Roboto Medium", 1, 18)); // NOI18N
        jlable8.setForeground(new java.awt.Color(233, 239, 192));
        jlable8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlable8.setText("Inbox");
        jlable8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlable8MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jlable8MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jlable8MouseExited(evt);
            }
        });

        javax.swing.GroupLayout InboxpaneLayout = new javax.swing.GroupLayout(Inboxpane);
        Inboxpane.setLayout(InboxpaneLayout);
        InboxpaneLayout.setHorizontalGroup(
            InboxpaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(InboxpaneLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlable8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        InboxpaneLayout.setVerticalGroup(
            InboxpaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jlable8, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
        );

        panel1.add(Inboxpane, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 132, 190, -1));

        paneenviadosjpanel.setBackground(new java.awt.Color(78, 148, 79));

        jlabel8.setFont(new java.awt.Font("Roboto Medium", 1, 18)); // NOI18N
        jlabel8.setForeground(new java.awt.Color(233, 239, 192));
        jlabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlabel8.setText("Enviados");
        jlabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlabel8MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jlabel8MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jlabel8MouseExited(evt);
            }
        });

        javax.swing.GroupLayout paneenviadosjpanelLayout = new javax.swing.GroupLayout(paneenviadosjpanel);
        paneenviadosjpanel.setLayout(paneenviadosjpanelLayout);
        paneenviadosjpanelLayout.setHorizontalGroup(
            paneenviadosjpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneenviadosjpanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        paneenviadosjpanelLayout.setVerticalGroup(
            paneenviadosjpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jlabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
        );

        panel1.add(paneenviadosjpanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 173, 190, -1));

        PanelMierdaSpam.setBackground(new java.awt.Color(78, 148, 79));

        jlabel9.setFont(new java.awt.Font("Roboto Medium", 1, 18)); // NOI18N
        jlabel9.setForeground(new java.awt.Color(233, 239, 192));
        jlabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlabel9.setText("Spam");
        jlabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlabel9MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jlabel9MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jlabel9MouseExited(evt);
            }
        });

        javax.swing.GroupLayout PanelMierdaSpamLayout = new javax.swing.GroupLayout(PanelMierdaSpam);
        PanelMierdaSpam.setLayout(PanelMierdaSpamLayout);
        PanelMierdaSpamLayout.setHorizontalGroup(
            PanelMierdaSpamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelMierdaSpamLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        PanelMierdaSpamLayout.setVerticalGroup(
            PanelMierdaSpamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jlabel9, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
        );

        panel1.add(PanelMierdaSpam, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 214, 190, -1));

        panel_eliminados.setBackground(new java.awt.Color(78, 148, 79));

        label_eliminados.setFont(new java.awt.Font("Roboto Medium", 1, 18)); // NOI18N
        label_eliminados.setForeground(new java.awt.Color(233, 239, 192));
        label_eliminados.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_eliminados.setText("Eliminados");
        label_eliminados.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                label_eliminadosMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                label_eliminadosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                label_eliminadosMouseExited(evt);
            }
        });

        javax.swing.GroupLayout panel_eliminadosLayout = new javax.swing.GroupLayout(panel_eliminados);
        panel_eliminados.setLayout(panel_eliminadosLayout);
        panel_eliminadosLayout.setHorizontalGroup(
            panel_eliminadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_eliminadosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label_eliminados, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        panel_eliminadosLayout.setVerticalGroup(
            panel_eliminadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(label_eliminados, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
        );

        panel1.add(panel_eliminados, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 255, 190, -1));

        Panelcosojpane.setBackground(new java.awt.Color(78, 148, 79));

        label10.setFont(new java.awt.Font("Roboto Medium", 1, 18)); // NOI18N
        label10.setForeground(new java.awt.Color(233, 239, 192));
        label10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label10.setText("Contactos Favoritos");
        label10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                label10MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                label10MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                label10MouseExited(evt);
            }
        });

        javax.swing.GroupLayout PanelcosojpaneLayout = new javax.swing.GroupLayout(Panelcosojpane);
        Panelcosojpane.setLayout(PanelcosojpaneLayout);
        PanelcosojpaneLayout.setHorizontalGroup(
            PanelcosojpaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelcosojpaneLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label10, javax.swing.GroupLayout.DEFAULT_SIZE, 178, Short.MAX_VALUE)
                .addContainerGap())
        );
        PanelcosojpaneLayout.setVerticalGroup(
            PanelcosojpaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(label10, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
        );

        panel1.add(Panelcosojpane, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 338, -1, -1));

        Contactpane.setBackground(new java.awt.Color(78, 148, 79));

        addcont.setFont(new java.awt.Font("Roboto Medium", 1, 18)); // NOI18N
        addcont.setForeground(new java.awt.Color(233, 239, 192));
        addcont.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        addcont.setText("Agregar Contacto");
        addcont.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addcontMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                addcontMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                addcontMouseExited(evt);
            }
        });

        javax.swing.GroupLayout ContactpaneLayout = new javax.swing.GroupLayout(Contactpane);
        Contactpane.setLayout(ContactpaneLayout);
        ContactpaneLayout.setHorizontalGroup(
            ContactpaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ContactpaneLayout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addComponent(addcont)
                .addGap(19, 19, 19))
        );
        ContactpaneLayout.setVerticalGroup(
            ContactpaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(addcont, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        panel1.add(Contactpane, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 296, 190, -1));

        drafts.setBackground(new java.awt.Color(78, 148, 79));

        draftscoso.setFont(new java.awt.Font("Roboto Medium", 1, 18)); // NOI18N
        draftscoso.setForeground(new java.awt.Color(233, 239, 192));
        draftscoso.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        draftscoso.setText("Borradores");
        draftscoso.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                draftscosoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                draftscosoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                draftscosoMouseExited(evt);
            }
        });

        javax.swing.GroupLayout draftsLayout = new javax.swing.GroupLayout(drafts);
        drafts.setLayout(draftsLayout);
        draftsLayout.setHorizontalGroup(
            draftsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(draftsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(draftscoso, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        draftsLayout.setVerticalGroup(
            draftsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(draftscoso, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
        );

        panel1.add(drafts, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 378, 190, -1));

        jLabel22.setBackground(new java.awt.Color(78, 148, 79));
        jLabel22.setFont(new java.awt.Font("Roboto Medium", 1, 12)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(78, 148, 79));
        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/MailIcon.png"))); // NOI18N
        jLabel22.setText("M a i l");
        jLabel22.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        panel1.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, 130, 60));

        jSeparator4.setBackground(new java.awt.Color(78, 148, 79));
        jSeparator4.setForeground(new java.awt.Color(78, 148, 79));
        panel1.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 220, 20));

        panel.add(panel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 190, 640));

        jScrollPane1.setBorder(null);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        CONTENIDOCORREO.setBackground(new java.awt.Color(180, 225, 151));
        CONTENIDOCORREO.setFont(new java.awt.Font("Roboto Medium", 1, 12)); // NOI18N
        CONTENIDOCORREO.setForeground(new java.awt.Color(78, 148, 79));
        jScrollPane1.setViewportView(CONTENIDOCORREO);

        panel.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 130, 610, 500));

        INBOX.setBackground(new java.awt.Color(131, 189, 117));

        jScrollPane2.setBorder(null);

        Tablain.setBackground(new java.awt.Color(233, 239, 192));
        Tablain.setForeground(new java.awt.Color(78, 148, 79));
        Tablain.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Correos"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        Tablain.setGridColor(new java.awt.Color(78, 148, 79));
        Tablain.setRowHeight(25);
        Tablain.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TablainMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(Tablain);
        if (Tablain.getColumnModel().getColumnCount() > 0) {
            Tablain.getColumnModel().getColumn(0).setResizable(false);
        }

        jPanel15.setBackground(new java.awt.Color(78, 148, 79));

        jLabel9.setFont(new java.awt.Font("Roboto Medium", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(247, 246, 220));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Inbox");

        javax.swing.GroupLayout jPanel15Layout = new javax.swing.GroupLayout(jPanel15);
        jPanel15.setLayout(jPanel15Layout);
        jPanel15Layout.setHorizontalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel15Layout.setVerticalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout INBOXLayout = new javax.swing.GroupLayout(INBOX);
        INBOX.setLayout(INBOXLayout);
        INBOXLayout.setHorizontalGroup(
            INBOXLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(INBOXLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(INBOXLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 166, Short.MAX_VALUE)
                    .addComponent(jPanel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        INBOXLayout.setVerticalGroup(
            INBOXLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, INBOXLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 587, Short.MAX_VALUE)
                .addContainerGap())
        );

        panel.add(INBOX, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 0, 190, 640));

        jPanel16.setBackground(new java.awt.Color(180, 225, 151));

        jlabel52.setFont(new java.awt.Font("Roboto Medium", 1, 12)); // NOI18N
        jlabel52.setForeground(new java.awt.Color(78, 148, 79));

        javax.swing.GroupLayout jPanel16Layout = new javax.swing.GroupLayout(jPanel16);
        jPanel16.setLayout(jPanel16Layout);
        jPanel16Layout.setHorizontalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel16Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlabel52, javax.swing.GroupLayout.DEFAULT_SIZE, 466, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel16Layout.setVerticalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jlabel52, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        panel.add(jPanel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 80, 490, 30));

        jPanel17.setBackground(new java.awt.Color(180, 225, 151));

        SUBJECTLABEL.setFont(new java.awt.Font("Roboto Medium", 1, 14)); // NOI18N
        SUBJECTLABEL.setForeground(new java.awt.Color(78, 148, 79));

        javax.swing.GroupLayout jPanel17Layout = new javax.swing.GroupLayout(jPanel17);
        jPanel17.setLayout(jPanel17Layout);
        jPanel17Layout.setHorizontalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel17Layout.createSequentialGroup()
                .addComponent(SUBJECTLABEL, javax.swing.GroupLayout.DEFAULT_SIZE, 484, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel17Layout.setVerticalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(SUBJECTLABEL, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        panel.add(jPanel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 40, 490, 30));

        jPanel18.setBackground(new java.awt.Color(78, 148, 79));

        jLabel11.setFont(new java.awt.Font("Roboto Medium", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(233, 239, 192));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("De");

        javax.swing.GroupLayout jPanel18Layout = new javax.swing.GroupLayout(jPanel18);
        jPanel18.setLayout(jPanel18Layout);
        jPanel18Layout.setHorizontalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel18Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, 76, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel18Layout.setVerticalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        panel.add(jPanel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 80, 100, 30));

        jPanel19.setBackground(new java.awt.Color(78, 148, 79));

        jLabel10.setFont(new java.awt.Font("Roboto Medium", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(233, 239, 192));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Asunto");

        javax.swing.GroupLayout jPanel19Layout = new javax.swing.GroupLayout(jPanel19);
        jPanel19.setLayout(jPanel19Layout);
        jPanel19Layout.setHorizontalGroup(
            jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel19Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel19Layout.setVerticalGroup(
            jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        panel.add(jPanel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 40, 100, 30));

        DELETE.setBackground(new java.awt.Color(131, 189, 117));

        jScrollPane6.setBorder(null);

        DELETED.setBackground(new java.awt.Color(233, 239, 192));
        DELETED.setForeground(new java.awt.Color(78, 148, 79));
        DELETED.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Correos"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        DELETED.setGridColor(new java.awt.Color(78, 148, 79));
        DELETED.setRowHeight(25);
        DELETED.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DELETEDMouseClicked(evt);
            }
        });
        jScrollPane6.setViewportView(DELETED);
        if (DELETED.getColumnModel().getColumnCount() > 0) {
            DELETED.getColumnModel().getColumn(0).setResizable(false);
        }

        jPanel20.setBackground(new java.awt.Color(78, 148, 79));

        jLabel12.setFont(new java.awt.Font("Roboto Medium", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(247, 246, 220));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("Eliminados");

        javax.swing.GroupLayout jPanel20Layout = new javax.swing.GroupLayout(jPanel20);
        jPanel20.setLayout(jPanel20Layout);
        jPanel20Layout.setHorizontalGroup(
            jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel20Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel20Layout.setVerticalGroup(
            jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout DELETELayout = new javax.swing.GroupLayout(DELETE);
        DELETE.setLayout(DELETELayout);
        DELETELayout.setHorizontalGroup(
            DELETELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DELETELayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(DELETELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 166, Short.MAX_VALUE)
                    .addComponent(jPanel20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        DELETELayout.setVerticalGroup(
            DELETELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, DELETELayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 545, Short.MAX_VALUE)
                .addContainerGap())
        );

        panel.add(DELETE, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 30, 190, 610));

        SWPAM.setBackground(new java.awt.Color(131, 189, 117));

        jScrollPane7.setBorder(null);

        SABLASPAM.setBackground(new java.awt.Color(233, 239, 192));
        SABLASPAM.setForeground(new java.awt.Color(78, 148, 79));
        SABLASPAM.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Correos"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        SABLASPAM.setGridColor(new java.awt.Color(78, 148, 79));
        SABLASPAM.setRowHeight(25);
        SABLASPAM.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SABLASPAMMouseClicked(evt);
            }
        });
        jScrollPane7.setViewportView(SABLASPAM);
        if (SABLASPAM.getColumnModel().getColumnCount() > 0) {
            SABLASPAM.getColumnModel().getColumn(0).setResizable(false);
        }

        jPanel21.setBackground(new java.awt.Color(78, 148, 79));

        jLabel13.setFont(new java.awt.Font("Roboto Medium", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(233, 239, 192));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("Spam");

        javax.swing.GroupLayout jPanel21Layout = new javax.swing.GroupLayout(jPanel21);
        jPanel21.setLayout(jPanel21Layout);
        jPanel21Layout.setHorizontalGroup(
            jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel21Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel21Layout.setVerticalGroup(
            jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout SWPAMLayout = new javax.swing.GroupLayout(SWPAM);
        SWPAM.setLayout(SWPAMLayout);
        SWPAMLayout.setHorizontalGroup(
            SWPAMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SWPAMLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(SWPAMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane7, javax.swing.GroupLayout.DEFAULT_SIZE, 166, Short.MAX_VALUE)
                    .addComponent(jPanel21, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        SWPAMLayout.setVerticalGroup(
            SWPAMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SWPAMLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel21, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane7, javax.swing.GroupLayout.DEFAULT_SIZE, 545, Short.MAX_VALUE)
                .addContainerGap())
        );

        panel.add(SWPAM, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 30, 190, 610));

        sent.setBackground(new java.awt.Color(131, 189, 117));

        jScrollPane8.setBorder(null);

        enviaditos.setBackground(new java.awt.Color(233, 239, 192));
        enviaditos.setForeground(new java.awt.Color(78, 148, 79));
        enviaditos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Correos"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        enviaditos.setGridColor(new java.awt.Color(78, 148, 79));
        enviaditos.setRowHeight(25);
        enviaditos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                enviaditosMouseClicked(evt);
            }
        });
        jScrollPane8.setViewportView(enviaditos);
        if (enviaditos.getColumnModel().getColumnCount() > 0) {
            enviaditos.getColumnModel().getColumn(0).setResizable(false);
        }

        jPanel22.setBackground(new java.awt.Color(78, 148, 79));

        jLabel14.setFont(new java.awt.Font("Roboto Medium", 1, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(233, 239, 192));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("Enviados");

        javax.swing.GroupLayout jPanel22Layout = new javax.swing.GroupLayout(jPanel22);
        jPanel22.setLayout(jPanel22Layout);
        jPanel22Layout.setHorizontalGroup(
            jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel22Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel22Layout.setVerticalGroup(
            jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout sentLayout = new javax.swing.GroupLayout(sent);
        sent.setLayout(sentLayout);
        sentLayout.setHorizontalGroup(
            sentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sentLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(sentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane8, javax.swing.GroupLayout.DEFAULT_SIZE, 166, Short.MAX_VALUE)
                    .addComponent(jPanel22, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        sentLayout.setVerticalGroup(
            sentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, sentLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel22, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane8, javax.swing.GroupLayout.DEFAULT_SIZE, 545, Short.MAX_VALUE)
                .addContainerGap())
        );

        panel.add(sent, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 30, 190, 610));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AquienenviaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AquienenviaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AquienenviaActionPerformed

    private void SubjectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubjectActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SubjectActionPerformed

    private void jlabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlabel2MouseClicked
        EnviarCuadrito.pack();
        EnviarCuadrito.setLocationRelativeTo(this);
        EnviarCuadrito.setModal(true);
        EnviarCuadrito.setVisible(true);
    }//GEN-LAST:event_jlabel2MouseClicked

    private void jlabel2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlabel2MouseEntered
    }//GEN-LAST:event_jlabel2MouseEntered

    private void jlabel2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlabel2MouseExited
    }//GEN-LAST:event_jlabel2MouseExited

    private void jlable8MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlable8MouseEntered
    }//GEN-LAST:event_jlable8MouseEntered

    private void jlable8MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlable8MouseExited
    }//GEN-LAST:event_jlable8MouseExited

    private void jlabel8MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlabel8MouseEntered
    }//GEN-LAST:event_jlabel8MouseEntered

    private void jlabel8MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlabel8MouseExited
    }//GEN-LAST:event_jlabel8MouseExited

    private void jlabel9MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlabel9MouseEntered
    }//GEN-LAST:event_jlabel9MouseEntered

    private void jlabel9MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlabel9MouseExited
    }//GEN-LAST:event_jlabel9MouseExited

    private void label_eliminadosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label_eliminadosMouseEntered
    }//GEN-LAST:event_label_eliminadosMouseEntered

    private void label_eliminadosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label_eliminadosMouseExited
    }//GEN-LAST:event_label_eliminadosMouseExited

    private void label10MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label10MouseEntered
    }//GEN-LAST:event_label10MouseEntered

    private void label10MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label10MouseExited
    }//GEN-LAST:event_label10MouseExited

    private void addcontMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addcontMouseEntered
    }//GEN-LAST:event_addcontMouseEntered

    private void addcontMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addcontMouseExited
    }//GEN-LAST:event_addcontMouseExited

    private void addcontMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addcontMouseClicked
        DefaultComboBoxModel m = (DefaultComboBoxModel) jComboBox1.getModel();
        m.removeAllElements();
        for (Persona pers : Main.ListUssers) {
            if (pers.getID() != Main.ListUssers.get(indexCuenta).getID() && !contactosId.contains(pers.getID())) {
                m.addElement(pers);
            }
        }

        AgregarCuadrito.pack();
        AgregarCuadrito.setLocationRelativeTo(this);
        AgregarCuadrito.setModal(true);
        AgregarCuadrito.setVisible(true);
    }//GEN-LAST:event_addcontMouseClicked

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        ponerContacto();
        Cargarcontac();
        JOptionPane.showMessageDialog(this, "Contacto Agregado", "Exito", JOptionPane.INFORMATION_MESSAGE);
        AgregarCuadrito.setVisible(false);
    }//GEN-LAST:event_jLabel6MouseClicked

    private void label10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label10MouseClicked
        DefaultListModel listm = (DefaultListModel) jList1.getModel();
        listm.removeAllElements();
        for (Integer integer : contactosId) {
            for (Persona pers : Main.ListUssers) {
                if (pers.getID() == integer) {
                    listm.addElement(pers);
                }
            }
        }
        Contactos.pack();
        Contactos.setLocationRelativeTo(this);
        Contactos.setModal(true);
        Contactos.setVisible(true);
    }//GEN-LAST:event_label10MouseClicked

    private void GuardarDraftMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_GuardarDraftMouseClicked
        boolean ver = true;
        int id = 0;
        for (Correo correo : correos) {
            if (correo.getAsunto().equals(Subject.getText()) || correo.getCuerpo().equals(Body.getText()) || correo.getRecipiente().equals(Aquienenvia.getText())) {
                ver = false;
                id = correo.getIdCorreo();
            }
        }
        if (ver) {
            ponerBorrador();
            Body.setText("");
            Aquienenvia.setText("");
            Subject.setText("");
            EnviarCuadrito.setVisible(false);
            JOptionPane.showMessageDialog(this, "Borrador Guardado", "Exito", JOptionPane.INFORMATION_MESSAGE);
        } else {
            updateBorrador(id);
            Body.setText("");
            Aquienenvia.setText("");
            Subject.setText("");
            EnviarCuadrito.setVisible(false);
            JOptionPane.showMessageDialog(this, "Borrador Actualizado", "Exito", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_GuardarDraftMouseClicked

    private void draftscosoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_draftscosoMouseClicked
        CargarDrafts();
        DefaultListModel listB = (DefaultListModel) jList2.getModel();
        listB.removeAllElements();
        for (Correo correo : correos) {
            if (correo.getIdCuenta() == Main.ListUssers.get(indexCuenta).getID()) {
                listB.addElement(correo.getAsunto());
            }
        }
        jList2.setModel(listB);
        CuadritoDrafts.pack();
        CuadritoDrafts.setLocationRelativeTo(this);
        CuadritoDrafts.setModal(true);
        CuadritoDrafts.setVisible(true);
    }//GEN-LAST:event_draftscosoMouseClicked

    private void draftscosoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_draftscosoMouseEntered
    }//GEN-LAST:event_draftscosoMouseEntered

    private void draftscosoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_draftscosoMouseExited
    }//GEN-LAST:event_draftscosoMouseExited

    private void jList2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jList2MouseClicked
        if (!jList2.isSelectionEmpty() && jList2.getSelectedIndices().length == 1 && evt.getClickCount() == 2) {
            for (Correo correo : correos) {
                if (correo.getAsunto().equals(jList2.getSelectedValue()) && correo.getIdCuenta() == Main.ListUssers.get(indexCuenta).getID()) {
                    Aquienenvia.setText(correo.getRecipiente());
                    Subject.setText(jList2.getSelectedValue());
                    Body.setText(correo.getCuerpo());
                }
            }
            CuadritoDrafts.setVisible(false);
            EnviarCuadrito.pack();
            EnviarCuadrito.setLocationRelativeTo(this);
            EnviarCuadrito.setModal(true);
            EnviarCuadrito.setVisible(true);
        }
    }//GEN-LAST:event_jList2MouseClicked

    private void sendMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sendMouseClicked

        Server server = new Server("smtp.office365.com", "587", Usser, Contraseña);
        server.conectar();
        try {
            LinkMail mail = new LinkMail(server.getSession());
            mail.addRecipient(Message.RecipientType.TO, new InternetAddress(Aquienenvia.getText()));
            mail.setSubject(Subject.getText());
            mail.setText(Body.getText());
            BodyPart parteTexto = new MimeBodyPart();
            parteTexto.setContent("<b>" + Body.getText() + "</b>", "text/html");

            MimeMultipart todaslasPartes = new MimeMultipart();
            todaslasPartes.addBodyPart(parteTexto);
            mail.setContent(todaslasPartes);
            mail.setFrom(server.getUsuario());

            server.enviarCorreo(mail);
            JOptionPane.showMessageDialog(this, "Correo Enviado", "Exito", JOptionPane.INFORMATION_MESSAGE);

            Body.setText("");
            Aquienenvia.setText("");
            Subject.setText("");
            EnviarCuadrito.setVisible(false);
        } catch (Exception e) {
        }

    }//GEN-LAST:event_sendMouseClicked

    private void TablainMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TablainMouseClicked
        if (Tablain.getSelectedRow() > -1) {
            try {
                int index = Bandejas.getMensajesInbox().length - (Tablain.getSelectedRow() + 1);
                SUBJECTLABEL.setText(Bandejas.getMensajesInbox()[index].getSubject());
                jlabel52.setText(Bandejas.getMensajesInbox()[index].getFrom()[0].toString());
                File html = new File("./correo.html");
                if (html.exists()) {
                    html.deleteOnExit();
                }
                CONTENIDOCORREO.setPage(new File("algo.html").toURI().toURL());
                Bandejas.partesCorreo(Bandejas.getMensajesInbox()[index]);
                Hilo h = new Hilo(CONTENIDOCORREO, Bandejas);
                h.start();
            } catch (Exception e) {

            }
        }
    }//GEN-LAST:event_TablainMouseClicked

    private void jlable8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlable8MouseClicked
        try {                                     
            DefaultTableModel listInbox = (DefaultTableModel) Tablain.getModel();
            listInbox.setNumRows(0);
            int cosso = Bandejas.getMensajesInbox().length/16;
            
            try {
                for (int i = Bandejas.getMensajesInbox().length - 1; i >= cosso; i--) {
                    String[] row = new String[1];
                    row[0] = Bandejas.getMensajesInbox()[i].getSubject();
                    listInbox.addRow(row);
                    System.out.println(".");
                }
                Tablain.setModel(listInbox);
            } catch (Exception e) {
                
            }
            
            sent.setVisible(false);
            DELETE.setVisible(false);
            INBOX.setVisible(true);
            SWPAM.setVisible(false);
        } catch (MessagingException ex) {
        }
    }//GEN-LAST:event_jlable8MouseClicked

    private void jlabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlabel8MouseClicked
        try {                                     
            DefaultTableModel listInbox = (DefaultTableModel) enviaditos.getModel();
            listInbox.setNumRows(0);
            
            int cosso = Bandejas.getMensajesEnviados().length/16;
            
            
            try {
                for (int i = Bandejas.getMensajesEnviados().length - 1; i >= cosso; i--) {
                    String[] row = new String[1];
                    row[0] = Bandejas.getMensajesEnviados()[i].getSubject();
                    listInbox.addRow(row);
                }
                
                enviaditos.setModel(listInbox);
            } catch (Exception e) {
                
            }
            
            sent.setVisible(true);
            DELETE.setVisible(false);
            INBOX.setVisible(false);
            SWPAM.setVisible(false);
        } catch (MessagingException ex) {

        }
    }//GEN-LAST:event_jlabel8MouseClicked

    private void jlabel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlabel9MouseClicked
        try {                                     
            DefaultTableModel listInbox = (DefaultTableModel) SABLASPAM.getModel();
            listInbox.setNumRows(0);
            int cosso = Bandejas.getMensajesSpam().length/16;
            try {
                for (int i = Bandejas.getMensajesSpam().length - 1; i >= cosso; i--) {
                    String[] row = new String[1];
                    row[0] = Bandejas.getMensajesSpam()[i].getSubject();
                    listInbox.addRow(row);
                }
                SABLASPAM.setModel(listInbox);
            } catch (Exception e) {
                
            }
            sent.setVisible(false);
            DELETE.setVisible(false);
            INBOX.setVisible(false);
            SWPAM.setVisible(true);
        } catch (MessagingException ex) {

        }
    }//GEN-LAST:event_jlabel9MouseClicked

    private void label_eliminadosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label_eliminadosMouseClicked
        try {                                              
            DefaultTableModel listInbox = (DefaultTableModel) DELETED.getModel();
            listInbox.setNumRows(0);
            int cosso = Bandejas.getMensajesEliminados().length/16;
            
            try {
                for (int i = Bandejas.getMensajesEliminados().length - 1; i >= cosso; i--) {
                    String[] row = new String[1];
                    row[0] = Bandejas.getMensajesEliminados()[i].getSubject();
                    listInbox.addRow(row);
                }
                DELETED.setModel(listInbox);
            } catch (Exception e) {
                
            }
            
            sent.setVisible(false);
            DELETE.setVisible(true);
            INBOX.setVisible(false);
            SWPAM.setVisible(false);
        } catch (MessagingException ex) {

        }
    }//GEN-LAST:event_label_eliminadosMouseClicked

    private void DELETEDMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DELETEDMouseClicked
        if (DELETED.getSelectedRow() > -1) {
            try {
                int index = Bandejas.getMensajesEliminados().length - (DELETED.getSelectedRow() + 1);
                SUBJECTLABEL.setText(Bandejas.getMensajesEliminados()[index].getSubject());
                jlabel52.setText(Bandejas.getMensajesEliminados()[index].getFrom()[0].toString());
                File html = new File("./correo.html");
                if (html.exists()) {
                    html.deleteOnExit();
                }
                CONTENIDOCORREO.setPage(new File("algo.html").toURI().toURL());
                Bandejas.partesCorreo(Bandejas.getMensajesEliminados()[index]);
                Hilo h = new Hilo(CONTENIDOCORREO, Bandejas);
                h.start();
            } catch (Exception e) {

            }
        }
    }//GEN-LAST:event_DELETEDMouseClicked

    private void SABLASPAMMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SABLASPAMMouseClicked
        if (SABLASPAM.getSelectedRow() > -1) {
            try {
                int index = Bandejas.getMensajesSpam().length - (SABLASPAM.getSelectedRow() + 1);
                SUBJECTLABEL.setText(Bandejas.getMensajesSpam()[index].getSubject());
                jlabel52.setText(Bandejas.getMensajesSpam()[index].getFrom()[0].toString());
                File html = new File("./correo.html");
                if (html.exists()) {
                    html.deleteOnExit();
                }
                CONTENIDOCORREO.setPage(new File("algo.html").toURI().toURL());
                Bandejas.partesCorreo(Bandejas.getMensajesSpam()[index]);
                Hilo h = new Hilo(CONTENIDOCORREO, Bandejas);
                h.start();
            } catch (Exception e) {

            }
        }
    }//GEN-LAST:event_SABLASPAMMouseClicked

    private void enviaditosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_enviaditosMouseClicked
        if (enviaditos.getSelectedRow() > -1) {
            try {
                int index = Bandejas.getMensajesEnviados().length - (enviaditos.getSelectedRow() + 1);
                SUBJECTLABEL.setText(Bandejas.getMensajesEnviados()[index].getSubject());
                jlabel52.setText(Bandejas.getMensajesEnviados()[index].getFrom()[0].toString());
                File html = new File("./correo.html");
                if (html.exists()) {
                    html.deleteOnExit();
                }
                CONTENIDOCORREO.setPage(new File("algo.html").toURI().toURL());
                Bandejas.partesCorreo(Bandejas.getMensajesEnviados()[index]);
                Hilo h = new Hilo(CONTENIDOCORREO, Bandejas);
                h.start();
            } catch (Exception e) {

            }
        }
    }//GEN-LAST:event_enviaditosMouseClicked

    public void CargarDrafts() {
        Dba db = new Dba("C:\\Users\\wilme\\Desktop\\Q4-22\\Proyecto Programacion II\\ProyectoFinal\\DatosPrograma.accdb");
        db.conectar();
        correos = new ArrayList();
        try {
            db.query.execute("select * from Drafts");
            ResultSet rs = db.query.getResultSet();
            correos = new ArrayList();
            while (rs.next()) {
                Correo c = new Correo();
                c.setIdCorreo(rs.getInt("IdBorrador"));
                c.setIdCuenta(rs.getInt("IdCuenta"));
                c.setRecipiente(rs.getString("Recipiente"));
                c.setAsunto(rs.getString("Asunto"));
                c.setCuerpo(rs.getString("Body"));
                correos.add(c);

            }
        } catch (SQLException ex) {
        }
        db.desconectar();
    }

    public void Cargarcoruss() {
        Dba db = new Dba("C:\\Users\\wilme\\Desktop\\Q4-22\\Proyecto Programacion II\\ProyectoFinal\\DatosPrograma.accdb");
        db.conectar();
        correosUsuarios = new ArrayList();
        try {
            db.query.execute("select * from correos");
            ResultSet rs = db.query.getResultSet();
            correosUsuarios = new ArrayList();
            while (rs.next()) {
                CorreoUsuarios cu = new CorreoUsuarios();
                cu.setIdCorreo(rs.getInt("idCorreo"));
                cu.setIdCuenta(rs.getInt("idCuenta"));
                cu.setUsuario(rs.getString("correo"));
                cu.setContra(rs.getString("Contraseña"));

                correosUsuarios.add(cu);
            }
        } catch (SQLException ex) {
        }
        db.desconectar();
    }

    public void Cargarcontac() {
        Dba db = new Dba("C:\\Users\\wilme\\Desktop\\Q4-22\\Proyecto Programacion II\\ProyectoFinal\\DatosPrograma.accdb");
        db.conectar();
        contactosId = new ArrayList();
        try {
            db.query.execute("select * from Contactos");
            ResultSet rs = db.query.getResultSet();
            contactosId = new ArrayList();
            while (rs.next()) {
                if (rs.getInt("IdUsuario") == Main.ListUssers.get(indexCuenta).getID()) {
                    contactosId.add(rs.getInt("IdContacto"));
                }
            }
        } catch (SQLException ex) {
        }
        db.desconectar();
    }

    public void ponerContacto() {
        Dba db = new Dba("C:\\Users\\wilme\\Desktop\\Q4-22\\Proyecto Programacion II\\ProyectoFinal\\DatosPrograma.accdb");
        db.conectar();
        try {
            db.query.execute("insert into Contactos (IdUsuario,IdContacto) "
                    + "VALUES (" + Main.ListUssers.get(indexCuenta).getID() + ", " + ((Persona) jComboBox1.getSelectedItem()).getID() + ")");
            db.commit();
        } catch (Exception e) {

        }
    }

    public void ponerBorrador() {
        Dba db = new Dba("C:\\Users\\wilme\\Desktop\\Q4-22\\Proyecto Programacion II\\ProyectoFinal\\DatosPrograma.accdb");
        db.conectar();
        try {
            db.query.execute("insert into Drafts (IdCuenta,Recipiente,Asunto,Body) "
                    + "VALUES (" + Main.ListUssers.get(indexCuenta).getID() + ", '" + Aquienenvia.getText() + "', '" + Subject.getText() + "', '" + Body.getText() + "')");
            db.commit();
        } catch (Exception e) {

        }
    }

    public void updateBorrador(int id) {
        Dba db = new Dba("C:\\Users\\wilme\\Desktop\\Q4-22\\Proyecto Programacion II\\ProyectoFinal\\DatosPrograma.accdb");
        db.conectar();
        try {
            db.query.execute("update Drafts set Recipiente= '" + Aquienenvia.getText()
                    + "' , Asunto= '" + Subject.getText()
                    + "' , Body= '" + Body.getText()
                    + "' where IdBorrador= " + id);
            db.commit();
        } catch (SQLException ex) {
        }
        db.desconectar();

    }

    public void elimBorrador() {

    }

    public boolean Conectandoconlosdiosesdelasmatematicas() {
        try {
            session = javax.mail.Session.getInstance(props, new javax.mail.Authenticator(){
                protected PasswordAuthentication getPasswordAuthentication(){
                    return new PasswordAuthentication(Usser,Contraseña);
                }
            });
            store = session.getStore("imap");
            store.connect("outlook.office365.com", Usser, Contraseña);

            BandejadeEntrada = store.getFolder("INBOX");
            BandejadeEntrada.open(Folder.READ_WRITE);
            inboxM = BandejadeEntrada.getMessages();

            ElementosEnviados = store.getFolder("Elementos enviados");
            ElementosEnviados.open(Folder.READ_WRITE);
            enviadosM = ElementosEnviados.getMessages();

            ElementoEliminados = store.getFolder("Elementos eliminados");
            ElementoEliminados.open(Folder.READ_WRITE);
            eliminadosM = ElementoEliminados.getMessages();

            MierdaSpam = store.getFolder("Correo no deseado");
            MierdaSpam.open(Folder.READ_WRITE);
            spamM = MierdaSpam.getMessages();
            return true;
        } catch (Exception e) {
            System.out.println(Usser + " " + Contraseña);
            
        }
        return false;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CorreoCloudy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CorreoCloudy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CorreoCloudy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CorreoCloudy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CorreoCloudy(indexCuenta).setVisible(true);
            }
        });
    }
    private int xMouse;
    private int yMouse;
    private int bruh;
    private String Usser;
    private String Contraseña;
    private static int indexCuenta;
    private ArrayList<Correo> correos;
    private ArrayList<CorreoUsuarios> correosUsuarios;
    private ArrayList<Integer> contactosId;
    private Bandejas Bandejas;

    private Folder BandejadeEntrada;
    private Folder ElementoEliminados;
    private Folder MierdaSpam;
    private Folder ElementosEnviados;

    private Message[] inboxM;
    private Message[] eliminadosM;
    private Message[] spamM;
    private Message[] enviadosM;

    private Properties props;
    private Session session;
    private Store store;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDialog AgregarCuadrito;
    private javax.swing.JTextField Aquienenvia;
    private javax.swing.JTextArea Body;
    private javax.swing.JEditorPane CONTENIDOCORREO;
    private javax.swing.JDialog Contactos;
    private javax.swing.JPanel Contactpane;
    private javax.swing.JDialog CuadritoDrafts;
    private javax.swing.JPanel DELETE;
    private javax.swing.JTable DELETED;
    private javax.swing.JDialog EnviarCuadrito;
    private javax.swing.JLabel GuardarDraft;
    private javax.swing.JPanel INBOX;
    private javax.swing.JPanel Inboxpane;
    private javax.swing.JPanel PanelMierdaSpam;
    private javax.swing.JPanel Panelcosojpane;
    private javax.swing.JTable SABLASPAM;
    private javax.swing.JLabel SUBJECTLABEL;
    private javax.swing.JPanel SWPAM;
    private javax.swing.JTextField Subject;
    private javax.swing.JTable Tablain;
    private javax.swing.JLabel addcont;
    private javax.swing.JLabel coso;
    private javax.swing.JPanel drafts;
    private javax.swing.JLabel draftscoso;
    private javax.swing.JLabel encabezadosapo;
    private javax.swing.JTable enviaditos;
    private javax.swing.JPanel enviarcorreopanel;
    private javax.swing.JLabel headercosa;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JList<String> jList1;
    private javax.swing.JList<String> jList2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel20;
    private javax.swing.JPanel jPanel21;
    private javax.swing.JPanel jPanel22;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JLabel jlabel2;
    private javax.swing.JLabel jlabel52;
    private javax.swing.JLabel jlabel8;
    private javax.swing.JLabel jlabel9;
    private javax.swing.JLabel jlable8;
    private javax.swing.JLabel label10;
    private javax.swing.JLabel label_eliminados;
    private javax.swing.JPanel paneenviadosjpanel;
    private javax.swing.JPanel panel;
    private javax.swing.JPanel panel1;
    private javax.swing.JPanel panel_eliminados;
    private javax.swing.JLabel send;
    private javax.swing.JPanel sent;
    // End of variables declaration//GEN-END:variables
}
